Fix basket total double arithmetic issues when total should be zero
shopware5/shopware pull request #1027
Opened 2017-03-01 16:17 UTC by fixpunkt

## Description
Please describe your pull request:

* _Why is it necessary?_
We have use cases where the entire remaining value of the basket needs to be discounted. Shopware computes the basket total using double (i.e. binary floating point) arithmetic. A lot of common decimal fractions are periodic in binary, which means they cannot be represented exactly by doubles. Because of this, the result of adding a few simple decimal fractions may be off from the expected result by a small margin. In some particular constellations, this leads to the basket total being infinitesimally below zero when it should be exactly zero, which leads to Shopware rejecting the basket as invalid.
Additionally, even when we force Shopware to accept the basket as valid (by rejecting the `Shopware_Modules_Basket_sGetBasket_AllowEmptyBasket` event), the total will be rounded to negative zero by `sBasket::sGetAmount()` and totally nonsensical values like `-3.55` in `sBasket::sGetBasket()` (for which I'm currently preparing a separate PR that fixes this behaviour in `sArticles::sRound()`), both of which does not make any sense but is then rendered in the frontend nonetheless.

* _What does it improve?_
The pull request rounds the totals that are returned from `sBasket::sGetBasketArticles()` to two decimal places and coerces their values to be `0.0` when the FPU computes them to `-0.0`. It also modifies `sBasket::sGetAmount()` and `sBasket::sGetAmountArticles()` to always return positive zero when negative zero would normally be returned.

* _Does it have side effects?_
None observed.

| Questions        | Answers
| ---------------- | -------------------------------------------------------
| BC breaks?       | no
| Tests pass?      | yes
| Related tickets? | Don't know of any
| How to test?     | A unit test is enclosed with the PR.

2017-03-02 18:45 UTC, nlubisch requested changes

2017-03-02 18:45 UTC, nlubisch commented on tests/Functional/Core/sBasketTest.php
> +            $article = $resourceHelper->createArticle(array(
use short array syntax

2017-03-02 18:45 UTC, nlubisch commented on tests/Functional/Core/sBasketTest.php
> +        $resourceHelper = new \Shopware\Tests\Functional\Bundle\StoreFrontBundle\Helper();
import class

2017-03-02 19:02 UTC, samuelvogel commented on tests/Functional/Core/sBasketTest.php
> +        $resourceHelper = new \Shopware\Tests\Functional\Bundle\StoreFrontBundle\Helper();
There are no imports in this test class right now and Shopware does it the same way [here](https://github.com/shopware/shopware/blob/v5.2.20/tests/Functional/Core/sBasketTest.php#L2300) as well, so it should probably be fine for a single use.

2017-03-03 16:29 UTC, fixpunkt commented on tests/Functional/Core/sBasketTest.php
> +            $article = $resourceHelper->createArticle(array(
This would make this test inconsistent with the rest of the test case.

2017-04-13 15:27 UTC, marcop73 commented on engine/Shopware/Core/sBasket.php
> +    private static function roundTotal($total)
IMHO Is a private function instead of a private **static** function more suitable

2017-04-15 10:55 UTC, fixpunkt commented on engine/Shopware/Core/sBasket.php
> +    private static function roundTotal($total)
Thanks for your feedback.

Since it doesn't need `$this`, it is static by definition. The keyword makes this explicit. What's your reasoning for why this should be an instance method?

2017-07-10 09:43 UTC, htkassner commented
Thank you for your contribution. This will be released with our 5.3 version.

2017-07-10 09:43 UTC, closed without merging