Document order patch 1
shopware5/shopware pull request #1031
Opened 2017-03-02 09:20 UTC by JonidBendo

- Add Event after the positions are processed for the invoice generation
- Add set and get methods for the protected variables to allow further modifications for taxes and etc.

## Description
Please describe your pull request:
* Why is it necessary?
There is no other way to actually work/edit the invoice generation system

* What does it improve?
It allows plugin developers to use the event and modify the invoice details

* Does it have side effects?
If not used properly from the plugin developers it might break the invoice generation methods

| Questions        | Answers
| ---------------- | -------------------------------------------------------
| BC breaks?       | no
| Tests pass?      | yes
| Related tickets? | If this PR fixes an existing [Issue](https://issues.shopware.com) ticket, please add its complete issue URL.
| How to test?     | Simply call the event in a plugin...

2017-03-02 18:36 UTC, nlubisch requested changes

2017-03-02 18:36 UTC, nlubisch commented on engine/Shopware/Models/Document/Order.php
> +        $parameters = Shopware()->Events()->filter('DOCUMENT_ORDER_POSITIONS_PROCESSED', $parameters, array('subject' => $this, 'params' => $parameters));
use short array syntax and chop the line down to improve the readability

2017-03-02 18:36 UTC, nlubisch commented on engine/Shopware/Models/Document/Order.php
> +        $parameters['positions']    = $this->_positions;
remove the identation before the values to provide a consistent code style

2017-03-02 18:36 UTC, nlubisch commented on engine/Shopware/Models/Document/Order.php
> +     * Se class parameters
typo

2017-03-02 18:36 UTC, nlubisch commented on engine/Shopware/Models/Document/Order.php
> +    private function setParameters( $parameters )
remove space before and after parameter

2017-03-02 18:37 UTC, nlubisch commented on engine/Shopware/Models/Document/Order.php
> +     * @return Array $parameters
return type to lower case

2017-11-02 14:02 UTC, OliverSkroblin commented
Hi @JonidBendo,
thanks for your pull request.

We merged your changes. The changes will be available in version 5.3.5

2017-11-02 14:02 UTC, closed without merging