In Validation and Form Attributes
shopware5/shopware pull request #1112
Opened 2017-05-04 09:06 UTC by egoist-dd

## Description

| Questions               | Answers |
|-------------------------|-------------------------------------------------------|
| Why?                    | Cast Page Value to valid Integer, to prevent wrong Data or Errors, Adding Form Attributes to View Data to Extend Forms with Attribute Fields |
| BC breaks?              |no |
| Tests exists & pass?    |no |
| Related tickets?        | - |
| How to test?            | - |
| Requirements met?       | - |

2017-05-04 11:37 UTC, mitelg requested changes

2017-05-04 11:37 UTC, mitelg commented on engine/Shopware/Controllers/Frontend/Forms.php
> +            'attribute'         => $form->getAttribute(),
I think this is not necessary

2017-05-04 11:37 UTC, mitelg commented
hey @egoist-dd 
thanks for your PR :+1: 

please resolve the conflicts and squash your commit to one

2017-05-08 08:43 UTC, egoist-dd commented on engine/Shopware/Controllers/Frontend/Forms.php
> +            'attribute'         => $form->getAttribute(),
why? the systems allows me to add attributes to forms, the system reads attributes from database, but the attributes where not send to the view :-|

2017-05-10 11:53 UTC, mitelg requested changes

2017-05-10 11:53 UTC, mitelg commented on engine/Shopware/Controllers/Frontend/Forms.php
> +            'attribute' => $form->getAttribute(),
please provide this change in separate PR

2017-05-11 10:22 UTC, merged