Plugin Changelog for local plugins
shopware5/shopware pull request #1186
Opened 2017-07-05 18:01 UTC by shyim

## Description

| Questions               | Answers |
|-------------------------|-------------------------------------------------------|
| Why?                    | Local plugins should have the same abilities like in store |
| BC breaks?              | no |
| Tests exists & pass?    | yes |
| Related tickets?        |  |
| How to test?            | Install latest version of https://github.com/shyim/shopware-profiler from github |
| Requirements met?       | Yep |

Screenshot:
![image](https://user-images.githubusercontent.com/6224096/27877863-8fdf43a0-61bc-11e7-9b17-73ce7485bacc.png)

plugin.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<plugin xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../engine/Shopware/Components/Plugin/schema/plugin.xsd">
    <label lang="de">ShyimProfiler</label>
    <label lang="en">ShyimProfiler</label>
    <version>1.1.0</version>
    <copyright>Shyim</copyright>
    <license>MIT</license>
    <link>https://github.com/shyim/shopware-profiler</link>
    <author>Shyim</author>
    <changelog version="1.1.0">
        <changes lang="en">
            <![CDATA[
                <h4>Performance Event Charts 🎉</h4>
                <ul>
                <li>Added event charts to show which events needs how long to execute</li>
                <li>Added overview of cache read/write/delete and a hit/miss metric</li>
                <li>Added new sidebar of security with all user informations and password encoders</li>
                <li>Added overview of container parameters to "Configuration" tab</li>
                <li>Added search form to developers.shopware.com</li>
                </ul>
            ]]>
        </changes>
    </changelog>
</plugin>
```

2017-07-06 07:04 UTC, mitelg requested changes

2017-07-06 07:04 UTC, mitelg commented on _sql/migrations/943-add-plugin-changelog.php
> +ALTER TABLE `s_core_plugins` ADD `changelog` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL AFTER `description`;
there is already a column `changes` 
I think it was created with intention to store the changelog. maybe you can use this?

2017-07-06 07:13 UTC, shyim commented on _sql/migrations/943-add-plugin-changelog.php
> +ALTER TABLE `s_core_plugins` ADD `changelog` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL AFTER `description`;
I guess I was drunken. I will change it later

2017-07-06 07:23 UTC, mitelg commented on _sql/migrations/943-add-plugin-changelog.php
> +ALTER TABLE `s_core_plugins` ADD `changelog` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL AFTER `description`;
I bet you were not :wink: :smile:

2017-07-06 08:06 UTC, shyim commented on _sql/migrations/943-add-plugin-changelog.php
> +ALTER TABLE `s_core_plugins` ADD `changelog` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL AFTER `description`;
@mitelg Captain fixed!

2017-07-06 08:50 UTC, mitelg approved these changes

2017-09-21 13:49 UTC, soebbing commented
Hi @shyim, we just merged your PR: https://github.com/shopware/shopware/commit/79856faf0fba0a5c80770a498597840d6a0b1e8f (and added a bit of HTML sanitizing). 😉 

 Thank you again for your awesome help! 💙

2017-09-21 13:49 UTC, closed without merging