Have the plugin manager reload on fail
shopware5/shopware pull request #1307
Opened 2017-10-12 12:00 UTC by niklasbuechner

### 1. Why is this change necessary?
When a plugin update fails the local plugin listing is not reloaded. The plugin will therefore still be listed under activated even though it gets disabled due to the failed update.
This can leave users confused since the plugin is listed as active but is not.

### 2. What does this change do, exactly?
It reloads the local plugin listing once a plugin update fails. Furthermore, it reloads the menu to remove disabled menu items.

### 3. Describe each step to reproduce the issue or behaviour.
Create a plugin which fails during the update process. Click update in the plugin manager's local plugin listing.

### 4. Please link to the relevant issues (if any).
None exists.

### 5. Which documentation changes (if any) need to be made because of this PR?
None.

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

By the way, I am a new Pickware team member.

2017-10-12 14:33 UTC, mitelg requested changes

2017-10-12 14:33 UTC, mitelg commented on Upgrade.md
> +* Adds missing handling of plugin update fails by reloading the plugin listing in the plugin manager window
please update our existing Upgrade files

2017-10-13 09:00 UTC, niklasbuechner commented on Upgrade.md
> +* Adds missing handling of plugin update fails by reloading the plugin listing in the plugin manager window
The correct file has been updated.

2017-10-13 09:56 UTC, mitelg approved these changes

2018-10-12 07:50 UTC, closed without merging