Prevent missing locale from crashing snippet import
shopware5/shopware pull request #1377
Opened 2017-11-15 14:45 UTC by hanneswernery

### 1. Why is this change necessary?

Right now if you import snippets to the db and if a specific entry in `s_core_locales`is missing, the whole import will crash with the following exception `Call to a member function getId() on null`.

### 2. What does this change do, exactly?

This PR adds a safeguard that checks if the requested locale object does in fact exist before importing a snippet for it. If no locale was found this specific snippet will be skipped. This way all remaining (and working) snippets can be imported normally.

### 3. Describe each step to reproduce the issue or behaviour.

If you delete a necessary locale from the db and try to import snippets, it will fail for all remaining snippets, that would normally work fine.

### 4. Please link to the relevant issues (if any).

### 5. Which documentation changes (if any) need to be made because of this PR?

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [X] I have squashed any insignificant commits
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

2017-11-15 14:49 UTC, mitelg requested changes

2017-11-15 14:49 UTC, mitelg commented on engine/Shopware/Components/Snippet/DatabaseHandler.php
> +                if (!$locale) {
shouldn't this be `if ($locale) {` ?

2017-11-15 14:53 UTC, hanneswernery commented on engine/Shopware/Components/Snippet/DatabaseHandler.php
> +                if (!$locale) {
Of course id should. Thanks!

2017-11-16 07:21 UTC, mitelg approved these changes

2017-11-16 08:25 UTC, hanneswernery commented
I've added a test that fails without the my changes in the `DatabaseHandler.php`.

2018-04-11 08:28 UTC, cjuner commented
@hanneswernery, please rebase for Shopware 5.5.

2018-08-09 11:52 UTC, soebbing commented
Hi @hanneswernery, thank you very much for your contribution! 🎉

2018-08-09 11:52 UTC, closed without merging