Amend Shopware/Models/Order/Detail::getTaxRate
shopware5/shopware pull request #1388
Opened 2017-11-19 14:20 UTC by JoshuaBehrens

### 1. Why is this change necessary?
Because it is a major ~~upfuck~~ discomfort for IDEs and their users.

### 2. What does this change do, exactly?
It just fixes a type in phpDoc.

### 3. Describe each step to reproduce the issue or behaviour.
```php
/** @var $model \Shopware\Models\Order\Detail */
$model = /* --- */;
$taxRate = $model->getTaxRate(); // this gets hinted as string
var_dump($taxRate); // this will dump float
```

### 4. Please link to the relevant issues (if any).
None.

### 5. Which documentation changes (if any) need to be made because of this PR?
It is a documentation change.

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfill them.

2017-11-20 08:01 UTC, mitelg requested changes

2017-11-20 08:01 UTC, mitelg commented on engine/Shopware/Models/Order/Detail.php
>      public function getTaxRate()
the setter should also be changed then...

2017-11-20 09:09 UTC, JoshuaBehrens commented on engine/Shopware/Models/Order/Detail.php
>      public function getTaxRate()
Well I guess I did not think my ~~rant~~ amendment through.

2017-11-20 09:10 UTC, mitelg approved these changes

2017-11-21 14:17 UTC, MarcelSchmaeing commented
Hi,

thx. We merged this into the 5.4 Branch.

Greetings, 

Marcel

2017-11-21 14:17 UTC, closed without merging