misc - restrict .env access
shopware5/shopware pull request #1499
Opened 2018-02-01 13:23 UTC by teiling88

### 1. Why is this change necessary?

### 2. What does this change do, exactly?

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).

### 5. Which documentation changes (if any) need to be made because of this PR?

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

2018-02-01 13:54 UTC, soebbing requested changes

2018-02-01 13:54 UTC, soebbing commented on .htaccess
> +    RedirectMatch 404 /(web\/cache\/(config_\d+\.json|all.less|.env))$
The "dot" in .env isn't backspace-escaped

2018-02-01 14:08 UTC, teiling88 commented
ist removed

2018-02-02 10:46 UTC, teiling88 commented on .htaccess
> +    RedirectMatch 404 /(autoload\.php|composer\.(json|lock|phar)|README\.md|UPGRADE-(.*)\.md|CONTRIBUTING\.md|eula.*\.txt|\.gitignore|.*\.dist|\.env.*)$
It works fine with my apache2.4 no .env is available.

2018-04-09 07:32 UTC, closed without merging

2018-04-09 07:41 UTC, mitelg commented
thanks @teiling88 :+1: :tada: