add article mode constants to models
shopware5/shopware pull request #1538
Opened 2018-02-22 10:35 UTC by buddhaCode

### 1. Why is this change necessary?

I'm always looking for the numbers. Nobody would expect them in /themes/Frontend/Bare/frontend/checkout/cart_item.tpl. I think the right place is the model.

### 2. What does this change do, exactly?

Reducing developer pain.

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).

### 5. Which documentation changes (if any) need to be made because of this PR?

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2018-02-22 10:43 UTC, buddhaCode commented
I added the constants via an interface. This maybe breaks with the OO design. There are other ways:

- introduce a new abstract class and let the model classes extend this super class
- introduce a trait an use static varibales. Constants are not allowed in traits.

Personally, I think the interface is the most elegant way. But it's open for discussion.

2018-03-07 11:13 UTC, pascalheidmann-bedarf approved these changes

2018-03-08 13:46 UTC, buddhaCode commented
@shopwareBot No problem. I will do so. Any idea how to use the constants in smarty tpls?
`{if $mode eq constant('Shopware\Models\Article\Article::MODE_FOO')}` feels wrong and introduces dependencies between model and view.

2018-03-09 10:43 UTC, mitelg commented
@buddhaCode I would suggest simply assign the constants to the template in the index controller. so they are available everywhere

2018-03-22 11:35 UTC, buddhaCode commented
I'm on it. I just returned from vacation this week. So i couldn't spare some time on work.

2018-04-06 14:20 UTC, buddhaCode commented
I decided to use the constant function in templates. Loading the constants to view in the index controller does only help in the index controller. I think a Frontend Predispatch Event handler would work. But didn't know where to place it.

I was searching the code for the terms: modus, .modus, 'modus', "modus", getMode and setMode.

Hopefully, I didn't miss anything.

2018-04-09 08:02 UTC, pthreat commented
@buddhaCode Thanks a lot for your pull request, this looks really cool!
One small thing that would make it perfect, would be to use aliased class names, just like you did in:

engine/Shopware/Bundle/CustomerSearchBundleDBAL/Indexing/CustomerOrderGateway.php

Where you used a "use" statement and aliased the class name, I'm talking about the following:

use Shopware\Models\Article\Article; //If you could rename this to ProductModel it would be great.

Then on line 245: $query->setParameter(':articleModeProduct', Article::MODE_PRODUCT);

We would like that you alias in every other file just like you did it in this file.

Again, this is just great and we thank you for your contribution.

2018-04-09 09:16 UTC, buddhaCode commented
@pthreat as you wish ;)

2018-04-09 09:50 UTC, buddhaCode commented
sure thing

2018-04-09 09:50 UTC, buddhaCode commented on themes/Frontend/Bare/frontend/checkout/ajax_cart_item.tpl
> -{$IS_PRODUCT = 0}
sure thing

2018-04-09 09:52 UTC, mitelg commented on themes/Frontend/Bare/frontend/checkout/cart_item.tpl
> +{$IS_PRODUCT = constant('Shopware\Models\Article\Article::MODE_PREMIUM')}
this should be `MODE_PRODUCT` shouldn't it?

2018-04-09 09:59 UTC, buddhaCode commented on themes/Frontend/Bare/frontend/checkout/cart_item.tpl
> +{$IS_PRODUCT = constant('Shopware\Models\Article\Article::MODE_PREMIUM')}
guess so! sorry.

2018-04-10 11:07 UTC, pascalheidmann-bedarf requested changes
Several times this PR uses FQN for alias imported Models.
Also using constant() in templates (therefore having lots of function calls with identical input and output) looks not very clean.

2018-04-10 11:07 UTC, pascalheidmann-bedarf commented on engine/Shopware/Controllers/Backend/CanceledOrder.php
> +                WHERE s_order_basket.modus = $articleModeProduct
Why not using a prepared statement here?

2018-04-10 11:07 UTC, pascalheidmann-bedarf commented on engine/Shopware/Core/sAdmin.php
> +                    'modus' => Shopware\Models\Article\ProductModel::MODE_PAYMENT_SURCHARGE_DISCOUNT,
Does this even work? This should be just _ProductModel::MODE_PAYMENT_SURCHARGE_DISCOUNT_

2018-04-10 11:07 UTC, pascalheidmann-bedarf commented on engine/Shopware/Core/sBasket.php
> +            'modus' => Shopware\Models\Article\ProductModel::MODE_PAYMENT_SURCHARGE_DISCOUNT,
Again just _ProductModel::MODE_PAYMENT_SURCHARGE_DISCOUNT_

2018-04-10 11:07 UTC, pascalheidmann-bedarf commented on engine/Shopware/Core/sBasket.php
> +            if ($getArticles[$key]['modus'] == Shopware\Models\Article\ProductModel::MODE_PRODUCT) {
And again _ProductModel::MODE_PRODUCT_

2018-04-10 11:07 UTC, pascalheidman-bedarf commented on themes/Frontend/Bare/frontend/checkout/ajax_cart_item.tpl
> +{ @deprecated, use contants instead }
Why deprecating and not using those variables? Using those variables looks far more clean than using everytime a constant-lookup

2018-04-11 07:57 UTC, buddhaCode commented on engine/Shopware/Controllers/Backend/CanceledOrder.php
> +                WHERE s_order_basket.modus = $articleModeProduct
Actually, i missed this.

2018-04-11 07:58 UTC, buddhaCode commented on engine/Shopware/Core/sAdmin.php
> +                    'modus' => Shopware\Models\Article\ProductModel::MODE_PAYMENT_SURCHARGE_DISCOUNT,
This is really woking ;) Of course the FQM is not necessary.

2018-04-11 07:58 UTC, buddhaCode commented on themes/Frontend/Bare/frontend/checkout/ajax_cart_item.tpl
> +{ @deprecated, use contants instead }
I can see your point.

2018-04-11 08:00 UTC, buddhaCode commented
Thanks for your review @pascalheidman-bedarf. I made some changes.

2018-05-17 07:33 UTC, cm-springlane commented
Isn't mode 10 (in your code MODE_BUNDLE_ARTICLE) the bundle rebate? Perhaps the constant could be named accordingly to avoid confusion.

2018-05-17 09:53 UTC, buddhaCode commented
Yes, your absolutly right. Sorry for the mistake. Thanks for the review, @cm-springlane.

2018-07-31 09:22 UTC, buddhaCode commented
@shopwareBot Are there any chances for this PR to get merged?

2018-11-28 12:57 UTC, PaddyS commented
Hey @buddhaCode,

can you please rebase your branch to the current 5.5?
We **might** have a look at it soon. :-)

2018-11-28 14:07 UTC, buddhaCode commented
@PaddyS Puh never rebased something before. But i'll try. I'm on vacation for the next 1,5 weeks. I'll give it a try when I returned.

2019-04-26 15:17 UTC, buddhaCode commented
@PaddyS I tried to squash and rebase today. But there are waaaaaaaay too many changes to fix them all. Sorry. I will close the PR.

2019-04-26 15:17 UTC, closed without merging