Added clearing of old note entries
shopware5/shopware pull request #1628
Opened 2018-04-10 20:38 UTC by shyim

### 1. Why is this change necessary?
There are currently many old expired notes, which cant be used anymore

### 2. What does this change do, exactly?
Removes expired notes

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).
https://issues.shopware.com/issues/SW-21514

### 5. Which documentation changes (if any) need to be made because of this PR?

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

2018-04-11 06:36 UTC, tinect requested changes
... removed ... wrote inside

2018-04-11 06:39 UTC, tinect requested changes

2018-04-11 06:39 UTC, tinect commented on engine/Shopware/Plugins/Default/Frontend/CronRefresh/Bootstrap.php
> +        $sql = 'DELETE FROM s_order_notes WHERE datum < DATE_SUB(NOW(), INTERVAL 1 YEAR) AND userID = 0';
what about sUniqueID?
What I mean: user will get an sUniqueID.
* User isn't logged in
* User puts product in note -> sUniqueID is filled, userID=0
* User logs in
* User see product which he added not-loggedin, but userID stays empty

So Idea: Update userID for defined sUniqueID, too, before clearing users note

2018-04-11 11:35 UTC, aragon999 commented on engine/Shopware/Plugins/Default/Frontend/CronRefresh/Bootstrap.php
> +        if (0 === $maximumReferrerAge) {
Why convert to Yoda Style?

2018-04-11 11:35 UTC, teiling88 commented
Please run php-cs-fixer with the actual settings :-)

2018-04-11 11:38 UTC, shyim commented on engine/Shopware/Plugins/Default/Frontend/CronRefresh/Bootstrap.php
> +        if (0 === $maximumReferrerAge) {
php-cs-fixer run with old config :D

2018-04-11 18:46 UTC, shyim commented on engine/Shopware/Plugins/Default/Frontend/CronRefresh/Bootstrap.php
> +        $sql = 'DELETE FROM s_order_notes WHERE datum < DATE_SUB(NOW(), INTERVAL 1 YEAR) AND userID = 0';
This problem was also without this pull request. I have added a migration of note entries after user login :+1: https://github.com/shopware/shopware/pull/1628/commits/d2df7beba86bcd7488d7f86d5c23640283a6496d

2018-04-12 06:40 UTC, mitelg commented on engine/Shopware/Core/sAdmin.php
> +            $this->db->query('UPDATE s_order_notes SET userID = ? WHERE sUniqueID = ? AND userID = 0', [
please use the dbal connection and named parameters

2018-04-12 06:41 UTC, mitelg commented on engine/Shopware/Core/sAdmin.php
> +     * @throws Enlight_Event_Exception
theses exception are not directly thrown in this method

2018-04-12 06:41 UTC, mitelg commented on engine/Shopware/Plugins/Default/Frontend/CronRefresh/Bootstrap.php
> +     * @throws \Doctrine\DBAL\DBALException
this exception is not thrown directly in this method

2018-04-12 07:22 UTC, shyim commented on engine/Shopware/Core/sAdmin.php
> +     * @throws Enlight_Event_Exception
PhpStorm said it 😢. I will change it later (mitelg > phpstorm inspections)

2019-02-18 12:55 UTC, closed without merging