Add possibility to configure a price group as "cross article"
shopware5/shopware pull request #1654
Opened 2018-05-03 08:53 UTC by windaishi

### 1. Why is this change necessary?
If you assign an article to a price group, the quantity to calculate the discount for the price group is based on how many items of exactly this article are in the basket. Neither does it consider variants of this article nor any other articles in the same price group.

### 2. What does this change do, exactly?
This PR allows you to define a scale of discount across multiple articles. The discount level is calculated depending on the total number of (different) articles of the same price group. To achieve this, a price group can be configured to be 'cross article'.

It also adds a line to the price block in the frontend detail page that shows how many articles of this price groups are in the basket already.

### 3. Describe each step to reproduce the issue or behaviour.
N/A

### 4. Please link to the relevant issues (if any).
N/A

### 5. Which documentation changes (if any) need to be made because of this PR?
There section about price groups config should be extended by a paragraph explaining what the config 'cross article' means.

### 6. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2019-02-05 15:37 UTC, fixpunkt commented
@windaishi would you mind rebasing this onto 5.6?

2019-03-05 14:51 UTC, shyim commented
Hey @windaishi,
could you rebase it to 5.6? :blue_heart:

2019-03-05 15:26 UTC, hlohaus requested changes

2019-03-05 15:26 UTC, hlohaus commented on _sql/migrations/1402-cross-article-price-groups.php
> +            ADD crossArticle
maybe lower_underscore better?

2019-03-05 15:28 UTC, hlohaus commented on _sql/migrations/1402-cross-article-price-groups.php
> +class Migrations_Migration1402 extends Shopware\Components\Migrations\AbstractMigration
The number is duplicate so the tests doesn't work

2019-03-07 14:12 UTC, windaishi commented
I have rebase the PR to 5.6 branch. It's ready to merge ;)

2019-03-07 15:32 UTC, windaishi commented
Maybe someone can tell me why the travis tests are failing?

2019-03-07 20:11 UTC, mitelg commented on engine/Shopware/Bundle/StoreFrontBundle/Struct/Product/PriceGroup.php
> +    protected $crossArticle;
can we please name it `crossProduct` ? :blush:

2019-03-07 20:17 UTC, mitelg commented on engine/Shopware/Core/sBasket.php
> +    public function getPriceGroupBasketItemsQuantity($priceGroupId)
why does it have to be yet another public method in the basket core class? I know there is no cart bundle or such thing, but adding more public API to the core classes makes it even harder to refactor them in the future. I would suggest to introduce a small service for this

2019-03-07 20:18 UTC, mitelg commented on engine/Shopware/Bundle/StoreFrontBundle/Struct/Product/PriceGroup.php
> +    protected $crossArticle;
please fix the other occurrences, too

2019-03-08 17:12 UTC, windaishi commented on engine/Shopware/Core/sBasket.php
> +    public function getPriceGroupBasketItemsQuantity($priceGroupId)
Well, what about putting this method into the service `\Shopware\Components\Cart\BasketHelper`? It seems like creating a whole new service is just to much for this simple sql query.

2019-03-08 17:39 UTC, shyim commented on engine/Shopware/Core/sBasket.php
> +    public function getPriceGroupBasketItemsQuantity($priceGroupId)
That would mean we have to break the interface

2019-03-12 09:46 UTC, windaishi commented
> Also, please can you add everywhere types?

I was unsure about that. So I assume every new PR from now should have typehints everywhere?

2019-03-12 10:03 UTC, mitelg commented
@windaishi only if the PR has the 5.6 branch as target :wink:

2019-03-12 13:42 UTC, windaishi commented
Dear reviewers. I have implemented all requested changes. May you have another look?

2019-03-12 16:13 UTC, uehler commented on engine/Shopware/Components/Cart/PriceGroupCartItemsQuantityCalculator.php
> +    public function __construct($dbalConnection, $session)
missing type hints

2019-03-12 16:43 UTC, shyim commented on engine/Shopware/Bundle/StoreFrontBundle/Gateway/DBAL/FieldHelper.php
> +     * @param QueryBuilder         $queryBuilder
Since you typehinted everything in method signature you can remove the phpdoc.  Can you remove it also for all other methods you added?

2019-03-12 16:45 UTC, shyim commented on engine/Shopware/Controllers/Frontend/Detail.php
> +        Shopware()->Plugins()->Controller()->ViewRenderer()->setNoRender();
```suggestion
        $this->Front()->Plugins()->ViewRenderer()->setNoRender();
```

2019-03-12 16:45 UTC, shyim commented on engine/Shopware/Controllers/Frontend/Detail.php
> +        $this->View()->setScope(null);
Is here any reason why setting a scope?

2019-03-12 16:47 UTC, shyim commented on snippets/frontend/detail/data.ini
> +priceGroupCartItemsQuantity/pre = "You already have"
It makes the huge pain to translate that. Is there any reason why it can't be one single snippet

2019-03-12 16:48 UTC, shyim commented on themes/Frontend/Responsive/frontend/_public/src/js/jquery.price-group-cart-items-quantity.js
> +        onAddArticle: function () {
Please add some $.publish events

2019-03-12 16:49 UTC, shyim commented on themes/Frontend/Responsive/frontend/_public/src/less/_modules/detail.less
> +            margin-top: 6px;
unitize!

2019-03-12 16:49 UTC, shyim commented on themes/Frontend/Responsive/frontend/_public/src/js/jquery.price-group-cart-items-quantity.js
> +            getPriceGroupCartItemsQuantityUrl: window.controller['ajax_get_price_group_basket_items_quantity'],
Can we move that to a data variable? So we don't have another global variable

2019-03-12 18:17 UTC, windaishi commented on engine/Shopware/Components/Cart/PriceGroupCartItemsQuantityCalculator.php
> +    public function __construct($dbalConnection, $session)
Well, the typehints are missing intentionally. The dependencies passed into this services are services with no definition via interface. If someone replaces the services with an own implementation, this implementation may not be an instance of the original services classes. Therefore the typehints would cause a false-positive error.

2019-03-12 18:29 UTC, windaishi commented on snippets/frontend/detail/data.ini
> +priceGroupCartItemsQuantity/pre = "You already have"
I will try to ;)

2019-03-12 18:40 UTC, windaishi commented on engine/Shopware/Bundle/StoreFrontBundle/Gateway/DBAL/FieldHelper.php
> +     * @param QueryBuilder         $queryBuilder
Then I can completely drop all the DocComments because is would just contain the variable names of the parameters.
Therefore I strongly suggest to keep the types in the DocComments, even when they contains redundant information. 
Should I also remove the `@return` tags? What about types like `int[]` or `mixed`?
So, are you sure about that decision? Will this be the new style for the whole Shopware code?

2019-03-12 18:43 UTC, windaishi commented on themes/Frontend/Responsive/frontend/_public/src/js/jquery.price-group-cart-items-quantity.js
> +        onAddArticle: function () {
What do you mean? Sorry, I am not very used to developing jquery plugins for Shopware.

2019-03-12 19:03 UTC, soebbing commented on engine/Shopware/Bundle/StoreFrontBundle/Gateway/DBAL/FieldHelper.php
> +     * @param QueryBuilder         $queryBuilder
Shopware will remove all typehints only containing the same information as in the function signature itself. So classes, interfaces, etc can be dropped, `array` itself as well. `int []`, `string[]` contain additional information, they are preserved by our phpcs config. The same is true for return types in Shopware 5.6.

2019-03-12 19:07 UTC, windaishi commented on themes/Frontend/Responsive/frontend/_public/src/js/jquery.price-group-cart-items-quantity.js
> +            getPriceGroupCartItemsQuantityUrl: window.controller['ajax_get_price_group_basket_items_quantity'],
Could you please explain that? `getPriceGroupCartItemsQuantityUrl` isn't a global variable, is it? How else should it be done? I wanted to do it similar to how other plugins do it.

2019-03-12 20:16 UTC, shyim commented on themes/Frontend/Responsive/frontend/_public/src/js/jquery.price-group-cart-items-quantity.js
> +        onAddArticle: function () {
Similar to this https://github.com/shopware/shopware/blob/5.5/themes/Frontend/Responsive/frontend/_public/src/js/jquery.add-article.js#L127

So theme developers can do something when the event is fired

2019-03-12 20:19 UTC, shyim commented on themes/Frontend/Responsive/frontend/_public/src/js/jquery.price-group-cart-items-quantity.js
> +            getPriceGroupCartItemsQuantityUrl: window.controller['ajax_get_price_group_basket_items_quantity'],
As example set the default to null and add to that matching element data-getPriceGroupCartItemsQuantityUrl="{url foooo}". That will be replaced with that null. 

window.controller is a global array 😅

2019-03-12 20:20 UTC, shyim commented on snippets/frontend/detail/data.ini
> +priceGroupCartItemsQuantity/pre = "You already have"
Snippets can have also html and they are even parsed with Smarty

2019-03-12 20:29 UTC, aragon999 commented on engine/Shopware/Components/Cart/PriceGroupCartItemsQuantityCalculator.php
> +    public function __construct($dbalConnection, $session)
If one would replace `connection` with a non instance of `\Doctrine\DBAL\Connection` Shopware will probably explode :-)

2019-03-13 10:34 UTC, windaishi commented on engine/Shopware/Bundle/StoreFrontBundle/Gateway/DBAL/FieldHelper.php
> +     * @param QueryBuilder         $queryBuilder
Okay, thank you for explanation.

2019-03-13 10:36 UTC, windaishi commented on snippets/frontend/detail/data.ini
> +priceGroupCartItemsQuantity/pre = "You already have"
I did not want to put class-names in the snippets, as they are used by the corresponding smarty plugin. If I put them in the snippets, they would be hidden forever. I have thought about another solution, you can have a look at that.

2019-03-13 10:46 UTC, windaishi commented on themes/Frontend/Responsive/frontend/_public/src/js/jquery.price-group-cart-items-quantity.js
> +            getPriceGroupCartItemsQuantityUrl: window.controller['ajax_get_price_group_basket_items_quantity'],
> window.controller is a global array 😅
Ah sorry, I somehow overlooked that while reading your comment.

2019-03-13 16:34 UTC, windaishi commented
I tried to fix you remarks. You can have another look.

2019-03-13 20:02 UTC, mitelg commented on _sql/migrations/1610-cross-article-price-groups.php
> +                 VARCHAR(255) COLLATE utf8_unicode_ci NOT NULL'
the doctrine model annotation for this column needs the change as well 😉 

besides that, really really nice work! 👍

2019-03-14 09:53 UTC, mitelg approved these changes

2019-03-18 09:42 UTC, windaishi commented
Done

Am Fr., 15. März 2019 um 09:14 Uhr schrieb shopwareBot <
notifications@github.com>:

> Thanks for your Contribution! 💙
> Can you please squash your commits?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/shopware/shopware/pull/1654#issuecomment-473196248>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AF8aP3fnuamPHOzLwFcbYBhVjtEzUCoRks5vW1Z6gaJpZM4Twtga>
> .
>

2019-03-18 09:42 UTC, windaishi commented
Done

2019-05-17 16:09 UTC, fixpunkt commented
As discussed, we don't have any free capacity to implement the requested changes at the moment. Maybe someone from the community wants to step up?

2019-05-28 06:30 UTC, closed without merging