Improve caption of order overwrite confirmation dialog
shopware5/shopware pull request #1701
Opened 2018-07-04 11:44 UTC by windaishi

### 1. Why is this change necessary?
The caption of the dialog, that is shown in case of a possible data loss when saving the order, is not explaining what has happened.

![image](https://user-images.githubusercontent.com/6232639/42275297-20092ae4-7f90-11e8-8850-15db5601a07b.png)

### 2. What does this change do, exactly?
Improves the caption of the yes-no dialog. It now explains what actually has happened and why the saving of the order has been aborted.

![image](https://user-images.githubusercontent.com/6232639/42275241-f40c4e12-7f8f-11e8-97a6-2bdeed55b888.png)

### 3. Describe each step to reproduce the issue or behaviour.
Open the same order in two different backend sessions.
User 1: Save an order.
User 1: Save the same order again.

### 4. Please link to the relevant issues (if any).
N/A

### 5. Which documentation changes (if any) need to be made because of this PR?
N/A

### 6. Checklist

- [ ] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

2018-07-04 11:50 UTC, fixpunkt requested changes

2018-07-04 11:50 UTC, fixpunkt commented on snippets/backend/order/main.ini
> +overwriteOrder/message = "The order has been changed by another user in the meantime. To prevent overwriting these changes, saving the order was aborted. To show this changes, please close the order
> **these** changes

2018-07-04 11:50 UTC, fixpunkt commented on themes/Backend/ExtJs/backend/order/controller/list.js
> +            message: '{s name=overwrite_order/message}The order has been changed by another user in the meantime. To prevent overwriting these changes, saving the order was aborted. To show this chan
> **these** changes

2018-07-04 12:17 UTC, fixpunkt commented
This is quite important for us because overwriting other changes made to an order by Shopware WMS will cause severe issues, including stock corruption. So we really need the user to understand the consequences of clicking "Yes" here.

2018-07-12 12:38 UTC, shyim commented
thanks for your contribution @windaishi  +1 :tada: :blue_heart:

2018-07-12 12:38 UTC, closed without merging