Adding "shopware mail template name" to zend mail object
shopware5/shopware pull request #1763
Opened 2018-08-15 13:33 UTC by Isengo1989

### 1. Why is this change necessary?
There is only one real Event for checking the Mail before sending it `Enlight_Components_Mail_Send` - other events are only notify-events. Therefore it would be nice to know which Mail will be sent (sORDER / sREGISTERCONFIRMATION etc.) in case you want to send a mail with third party (mailchimp, emarsys etc.)

Right now there is no indicator whatsoever which mail will be sent. You can only differ these mails by their subject, which will eventually change (subshop, some admin etc.)

### 2. What does this change do, exactly?
It sets the MessageId ot the Zendmail object, which is never used anyways. It also catches Zend_Mail_Exceptions of setFrom.

### 3. Describe each step to reproduce the issue or behaviour.
Set setMessageId -> have the Shopware Template Name (sORDER / sREGISTERCONFIRMATION etc.) in the mail Object which can be accessed in `Enlight_Components_Mail_Send` 

### 4. Please link to the relevant issues (if any).

### 5. Which documentation changes (if any) need to be made because of this PR?

### 6. Checklist

- [x] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2018-08-15 14:05 UTC, tinect requested changes

2018-08-15 14:05 UTC, tinect commented on engine/Shopware/Components/TemplateMail.php
> +            $mail->setMessageId($mailModel->getName());
There are shops using this... ;-)
Generally, I would suggest not to _misuse_ any existing fields/props or something else. 

Please extend Mail-Object or something else.

2018-08-15 14:35 UTC, Isengo1989 commented on engine/Shopware/Components/TemplateMail.php
> +            $mail->setMessageId($mailModel->getName());
@tinect sure, you're right. I found no usage in the core, so I thought this could be done quick. I will extend the Mail Object.

2018-08-15 19:47 UTC, Isengo1989 commented on engine/Shopware/Components/TemplateMail.php
> +            $mail->setMessageId($mailModel->getName());
@tinect adding the template to the header would not interfere with any functunality
![auswahl_103](https://user-images.githubusercontent.com/8600299/44169207-014af280-a0d4-11e8-9104-07a7924d0914.jpg)

Also it would allow to match the email later on with rich tools like emarsys. What do you think?

2018-08-16 05:28 UTC, tinect commented on engine/Shopware/Components/TemplateMail.php
> +            $mail->setMessageId($mailModel->getName());
Yes, great idea. Sounds good :-)

2018-08-16 08:46 UTC, Isengo1989 commented
Removed **setMessageId** and added the value to the **header** instead.

2018-08-16 10:22 UTC, Isengo1989 commented on engine/Shopware/Components/TemplateMail.php
> +            $mail->addHeader('Template', $mailModel->getName());
@shopwareBot too bad :( I will fix the Exceptions according to this https://framework.zend.com/manual/1.10/en/zend.exception.using.html

Would this work for you guys?
```php
    /**
     * Property for the template. Can be filled by setTemplate function.
     *
     * @var null
     */
    protected $_swTemplate = null;

   /**
     * @return null
     */
    public function getSwTemplate()
    {
        return $this->_swTemplate;
    }

    /**
     * @param null $swTemplate
     */
    public function setSwTemplate($swTemplate)
    {
        $this->_swTemplate = $swTemplate;
    }
```

2018-08-21 19:23 UTC, Isengo1989 commented
@shopwareBot done.

2018-08-21 20:00 UTC, shyim commented on engine/Library/Enlight/Components/Mail.php
> +    protected $Template = null;
properties starts with lower 😊

2018-08-21 20:16 UTC, Isengo1989 commented on engine/Library/Enlight/Components/Mail.php
> +    protected $Template = null;
@shyim argh this PR is cursed - well next try tmrw :laughing:

2018-09-11 19:22 UTC, shyim commented
@Isengo1989 please create with the newest commit a new pull request :)

2018-09-11 19:33 UTC, closed without merging

2018-09-11 19:41 UTC, shyim commented
Wrong rebase? :D

2018-09-11 19:50 UTC, Isengo1989 commented
> Wrong rebase? :D

WTF - was hab ich getan o.O

2018-09-11 19:54 UTC, Isengo1989 commented
Sorry my bad, I am not sure what I did. But I guess it was wrong. It was no rebase tho. I fetched the upstream as usual, merged the upstream/5.5 in my fork and then.

Well anyways - new PR is done ^^

2018-10-17 12:53 UTC, Isengo1989 commented
@mitelg what happend to the PR?

2018-10-18 11:58 UTC, mitelg commented
@Isengo1989 I don't know what you have done 🙂 you closed the PR somehow and I only closed the related things 😉
maybe you could just reopen a new clean PR

2018-10-18 13:10 UTC, Isengo1989 commented
> @Isengo1989 I don't know what you have done  you closed the PR somehow and I only closed the related things 
> maybe you could just reopen a new clean PR

I think I forced annother PR/Change and overwrote my changes here -.- The changes are nowhere to be found - damn it

Well I will have to create a new one I guess

2018-10-18 13:40 UTC, mitelg commented
yeah I think so :frowning_face: 
Unfortunately I cannot even re-open the PR