Readonly attributes in Backend
shopware5/shopware pull request #1878
Opened 2018-11-09 09:04 UTC by pascalheidman-bedarf

### 1. Why is this change necessary?
Sometimes you want to add a attribute that should not be editable for your users but still visible in backend. This allows to make that attribute be readonly.

### 2. What does this change do, exactly?
Adding a new attribute configuration option that marks that attribute as readonly. This setting is then used to disable the input field in extjs. Therefore changes by code are of course still possible

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).
PR https://github.com/shopware/shopware/pull/1645
https://issues.shopware.com/issues/SW-21676

### 5. Which documentation changes (if any) need to be made because of this PR?
New option "readonly" for attribute cru(d).

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2018-11-09 09:14 UTC, shyim commented on _sql/migrations/1444-add-readonly-to-attribute-field.php
> +INSERT IGNORE INTO s_core_snippets (namespace, shopID, localeID, name, value, created, updated, dirty) VALUES
Why.. Add them to the ini file

2018-11-09 09:21 UTC, pascalheidman-bedarf commented on _sql/migrations/1444-add-readonly-to-attribute-field.php
> +INSERT IGNORE INTO s_core_snippets (namespace, shopID, localeID, name, value, created, updated, dirty) VALUES
You are right. Copy & pasted from https://github.com/shopware/shopware/pull/1645 but using snippets directly is way better and even felt strange when copy & pasting the migration 🙈

2018-11-12 07:59 UTC, pascalheidman-bedarf commented on themes/Backend/ExtJs/backend/base/attribute/Shopware.attribute.Form.js
> +                disabled: attribute.get('readonly')
Wasn't aware of the differences between those. Changed it to the more adequate _readOnly_.

2018-11-12 08:58 UTC, pascalheidman-bedarf commented
@shopwareBot migrations added, tests now run as they should

2018-11-27 09:57 UTC, pascalheidman-bedarf commented
While all elements now work more or less, I feel like that the multi selection grid isn't the cleanest solution as there is no way to disable individual columns inside the grid (sorting & deleting). Those are set right in the `initComponent()` function.
I played a bit around with providing a `setReadOnly()` function (the `Ext.form.FieldContainer` component has none), but that is never invoked on itself and has the problem not being able to access the child elements in `initComponent()` - therefore you can't use it to create a valid initial state.
Any ideas?

Oh and Travis CI fails with a completely irrelevant file...

2018-11-28 13:30 UTC, mitelg commented
@pascalheidman-bedarf ups, there went something wrong :wink:

2018-11-28 13:41 UTC, pascalheidman-bedarf commented
@mitelg yeah... gladly I made a backup before. I feel like I will never get rebase right in the first try 😞 

@shopwareBot the multi selection contains both the selection/search field as well as the grid with all selected elements. Former is easy as it is an real input but latter is a complex thing that has controls for ordering and deleting elements which can't disabled on the fly. It feels not complete to not being able to change their state later.

2018-11-29 10:05 UTC, pascalheidman-bedarf commented
@shopwareBot good point with the batch processing. I will take a look at it!

Regarding `allowSorting`: I played around with that property as well as `allowDelete` and `allowAdd` which will disable all those functionality. Only problem I have is that changing those later don't propagate to change the behaviour on the fly. Therefore trying to push all that changes down to their respective element now.

2018-11-29 10:30 UTC, tinect requested changes

2018-11-29 10:30 UTC, tinect commented on themes/Backend/ExtJs/backend/base/attribute/field/Shopware.form.field.Grid.js
> +        console.log(columns);
this shouldn't be here?

2018-11-29 14:57 UTC, pascalheidman-bedarf commented
@shopwareBot the 5.6 branch isn't up to date is it?

Neither my local repo nor github find any missing commits and this would explain why `shopware/engine/Shopware/Controllers/Backend/Analytics.php` always fails in Travis CI

2019-01-08 14:28 UTC, Pmuckel commented
Hey @pascalheidman-bedarf,

thanks for your improvements! I tested them and they look pretty good. 

There need to be some things added, though:
Can you please gray out the readonly attributes e.g. in the article detail view? Otherwise it wouldn't be possible for the customer to detect a readonly attribute. Also, please check the attribute translations (need to be grayed out as well if readonly) and remove the delete-buttons of the multiple selection grid. 

Thanks in advance!

2019-01-16 09:09 UTC, pascalheidman-bedarf commented
@shopwareBot yep but not much time right now.

@Pmuckel will try to add those suggested indicators.

2019-03-19 08:04 UTC, hlohaus commented on engine/Shopware/Bundle/AttributeBundle/Service/DataPersister.php
> +        $results = $builder->execute()->fetchAll();
FETCH_COLUMN and you can save yourself the next lines.

2019-07-16 10:49 UTC, pascalheidman-bedarf commented
I rebased to current 5.6 as there were some collisions as the code is quite old now ;)
Seems like there have been a database error @ travis so maybe someone can rerun those tests?

2019-07-29 09:50 UTC, pascalheidman-bedarf commented
@shopwareBot fixed the PR.
The migration wasn't working anymore as there was already another migration with the same class name.

2019-10-02 12:10 UTC, shyim commented
Thanks for your Contribution! :blue_heart:

2019-10-02 12:10 UTC, closed without merging