Fix: DataTime Bug
shopware5/shopware pull request #1913
Opened 2018-12-07 11:22 UTC by BurstNeon

Fix: application crashed if isnt datatime but has Format like 3070-0408-121221

### 1. Why is this change necessary?
Plugins with a search function will Response Error: 503 - Service Unavailable

### 2. What does this change do, exactly?
Fixes the problem that a string in **String** format is no longer initialized as a **date**, cause execute further lines like shopware\engine\Shopware\Controllers\Backend\Application.php :
    --> error is not caught that it is a string
    $date = new DateTime($value);
    $value = $date->format('Y-m-d');

### 3. Describe each step to reproduce the issue or behaviour.
When entering a Format like "3070-0408-121221" or "3070-04131308-12111662221" on search bar with a plugin like Shopware example "SwagProductListingExtension."

### 4. Please link to the relevant issues (if any).

### 5. Which documentation changes (if any) need to be made because of this PR?
shopware\engine\Shopware\Controllers\Backend

### 6. Checklist

- [✅ ] I have written tests and verified that they fail without my change
- [✅ ] I have squashed any insignificant commits
- [✅ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [✅] I have read the contribution requirements and fulfil them.

2018-12-07 11:48 UTC, bcremer commented on engine/Shopware/Controllers/Backend/Application.php
> +                if(!is_a($value, 'DateTime')) {
Please use the `instanceof` operator here:

```
if (!$value instanceof \DateTime)
```

2018-12-07 11:52 UTC, BurstNeon commented on engine/Shopware/Controllers/Backend/Application.php
> +                if(!is_a($value, 'DateTime')) {
changed, lovely regards.

2018-12-07 11:53 UTC, shyim commented on engine/Shopware/Controllers/Backend/Application.php
> +                if(!is_a($value, 'DateTime')) {
And now squash your commits 😉

2018-12-12 07:00 UTC, nlubisch requested changes

2018-12-12 07:00 UTC, nlubisch commented on engine/Shopware/Controllers/Backend/Application.php
> +        /** @var catch wrong date conversion $errors */
This docblock makes no sense. Please remove it.

2018-12-12 07:03 UTC, nlubisch commented
Please squash your commits.
For a explanation about how to do it look here: https://davidwalsh.name/squash-commits-git

2018-12-13 10:47 UTC, soebbing commented on engine/Shopware/Controllers/Backend/Application.php
> +                if(!is_a($value, 'DateTime')) {
Why not use the `\DateTimeInterface`?

2018-12-17 08:04 UTC, closed without merging