Resolve one-to-many relations in backend applications
shopware5/shopware pull request #1931
Opened 2018-12-21 14:16 UTC by JoshuaBehrens

### 1. Why is this change necessary?
Without this fix it was not possible to save extjs models with a one-to-many relation. A specific backend application can extend the changed behaviour to make it work right away but this change had to be done on multiple applications.

### 2. What does this change do, exactly?
It extends the analysis of referenced models by loading models from arrays for a one-to-many relation.

### 3. Describe each step to reproduce the issue or behaviour.
Two levels of nested extjs relations is my understanding.

### 4. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2018-12-24 09:14 UTC, shyim commented
Hey @JoshuaBehrens,

thanks for the Contribution :blue_heart:.
Can you please rebase your Branch to the newest changes in the 5.5 Branch, so we can sure that the tests are passing :blush:

2019-01-03 14:07 UTC, pascalheidmann-bedarf requested changes
Pls add your change to the doc block

2019-01-03 14:19 UTC, JoshuaBehrens commented
@pascalheidman-bedarf Your comment is justified. I guess I need to simplify my production problem to have a good example for the doc block.

2019-01-28 13:26 UTC, shyim commented
Hey @JoshuaBehrens,
could you provide a Code-Example to archive the Issue? I have tested your Changes against the example plugin of https://developers.shopware.com/developers-guide/backend-components/associations/ and could not find any changes :)

2019-02-04 14:07 UTC, JoshuaBehrens commented
I have time for it this evening. I wanted to fresh up all the PRs this week :)

2019-02-05 09:00 UTC, JoshuaBehrens commented
I guess I worked down the application to the problem. I still have to anonymize it.

2019-02-14 10:09 UTC, shyim commented
I have tested your provided Plugin. Your change does not affect anything.

It still continues at owning side condition. https://github.com/shopware/shopware/blob/3d8fe7cfeddc935367eb2550ced7b1eb9e2eb8ce/engine/Shopware/Controllers/Backend/Application.php#L838

Are you sure with your change?

2019-02-28 15:09 UTC, PaddyS commented
Hey @JoshuaBehrens,

we're still not a hundred percent sure if we really want that.
Can you maybe provide an example plugin including the actual issue?
Like some case of "Here I'd like to save Foo, but that doesn't work at the moment".

This way we could check if this is an actual issue in Shopware or just a weird scenario, that could and **should** be solved with a different approach.

Doesn't have to be public here, PN in Gitter or anything would be fine as well.

Would that be possible?

2019-02-28 22:00 UTC, JoshuaBehrens commented
I will mail you guys with the original plugin then.

2019-06-26 09:05 UTC, pascalheidman-bedarf commented
Any chance that this will fixed/merged some day?

2019-10-20 22:38 UTC, JoshuaBehrens commented
To clear things up I've been traveling back in time (code-wise) when the original error happened and recreated it:

> Fatal error: Uncaught TypeError: Argument 1 passed to `FooBar\Models\ModelWithManyToOneRelationToArticle::setArticle()` must be an instance of `Shopware\Models\Article\Article`, `array` given, called in `/vendor/shopware/shopware/engine/Shopware/Components/Model/ModelEntity.php` on line 56 and defined in `/custom/plugins/FooBar/Models/ModelWithManyToOneRelationToArticle.php` on line 129

It can be hotfixed when you overwrite your controllers `resolveExtJsData` and unset the passed data at the key of the relation. `unset($data['article']);` so the relation is ignored. Not a real fix if you want to save it but a fix to stop the error from happening.

2019-10-24 14:55 UTC, shyim commented
I have discussed this PR with @JoshuaBehrens and it can be fixed with an `setOneToMany` ([example](https://github.com/shopware/shopware/blob/00b097df06ec124ab8399eaec403a06374802f18/engine/Shopware/Models/Shop/TemplateConfig/Element.php#L283)) in the model. This method is already used in many places for the same problem.

Would this fix also your problem @pascalheidmann-bedarf ?

2019-10-30 13:19 UTC, closed without merging