Fix SW-23403: remove business logic from order model
shopware5/shopware pull request #2008
Opened 2019-02-06 09:40 UTC by ITLEntwicklung

### 1. Why is this change necessary?
https://issues.shopware.com/issues/SW-23403

### 2. What does this change do, exactly?
Move the business logic from order model to service & doctrine subscriber

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).
https://issues.shopware.com/issues/SW-23403

### 5. Which documentation changes (if any) need to be made because of this PR?

### 6. Checklist

- [X] I have written tests and verified that they fail without my change
- [X] I have squashed any insignificant commits
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

2019-02-06 10:33 UTC, shyim requested changes

2019-02-06 10:33 UTC, shyim commented on engine/Shopware/Bundle/OrderBundle/Service/CalculationService.php
> +class CalculationService
Interface me :)

2019-02-06 10:33 UTC, shyim commented on engine/Shopware/Bundle/OrderBundle/Service/StockService.php
> +class StockService
Interface me

2019-02-06 10:33 UTC, shyim commented on engine/Shopware/Bundle/OrderBundle/Subscriber/ArticleStockSubscriber.php
> +            Events::preUpdate,
Use a specific Object event instead

2019-02-06 10:33 UTC, shyim commented on engine/Shopware/Bundle/OrderBundle/Subscriber/OrderRecalculationSubscriber.php
> +          Events::preUpdate,
Same here

2019-02-06 10:33 UTC, shyim commented on engine/Shopware/Models/Order/Detail.php
> +        // If you need to manually trigger the update please use the service.
Please call the new service here, so that's not Breaking Plugins

2019-02-06 10:33 UTC, shyim commented on engine/Shopware/Models/Order/Detail.php
>      public function afterInsert()
You can remove it directly. There is no change to edit that Part. And your Subscribers does the same thing :wink:

2019-02-06 10:33 UTC, shyim commented on engine/Shopware/Models/Order/Detail.php
>      public function beforeUpdate()
Same here

2019-02-06 10:43 UTC, bneumann97 commented
Squash the commits

2019-02-06 17:36 UTC, Fredwak commented on engine/Shopware/Models/Order/Detail.php
>      public function beforeUpdate()
forgotten ...

2019-02-06 17:36 UTC, Fredwak commented on engine/Shopware/Models/Order/Detail.php
>      public function afterInsert()
forgotten ...

2019-02-06 17:36 UTC, Fredwak commented on engine/Shopware/Models/Order/Detail.php
> +        // If you need to manually trigger the update please use the service.
the preUpdate in Model and preUpdate in subscriber got called.
The results of the calculation would be the same but the calculation will be processed twice.

2019-02-06 17:38 UTC, rommelfreddy approved these changes

2019-02-07 06:58 UTC, PaddyS commented
Still one commit to go. Would be highly appreciated if you could get rid of the second "merge" commit as well. 👍

2019-02-07 07:05 UTC, nlubisch requested changes
Tests would be really nice, too :)

2019-02-07 07:05 UTC, nlubisch commented on engine/Shopware/Bundle/OrderBundle/Service/StockService.php
> +            Shopware()->Models()->persist($article);
Replace Shopware()->Models() with 'models' service passed through the constructor

2019-02-07 07:05 UTC, nlubisch commented on engine/Shopware/Bundle/OrderBundle/Service/StockService.php
> +                Shopware()->Models()->persist($oldArticle);
Replace Shopware()->Models() with 'models' service passed through the constructor

2019-02-07 07:05 UTC, nlubisch commented on engine/Shopware/Bundle/OrderBundle/Service/StockService.php
> +                Shopware()->Models()->persist($newArticle);
Replace Shopware()->Models() with 'models' service passed through the constructor

2019-02-07 07:05 UTC, nlubisch commented on engine/Shopware/Bundle/OrderBundle/Service/StockService.php
> +            Shopware()->Models()->persist($article);
Replace Shopware()->Models() with 'models' service passed through the constructor

2019-02-07 07:05 UTC, nlubisch commented on engine/Shopware/Bundle/OrderBundle/Service/StockService.php
> +            $oldArticle = $this->getArticleByNumber($oldArticleNumber);
The part with $oldArticle and $newArticle underneath looks pretty much the same and can be extract into a new method with proper parameters.

2019-02-07 07:05 UTC, nlubisch commented on engine/Shopware/Bundle/OrderBundle/Service/StockService.php
> +            Shopware()->Models()->persist($article);
Replace Shopware()->Models() with 'models' service passed through the constructor

2019-02-07 07:05 UTC, nlubisch commented on engine/Shopware/Bundle/OrderBundle/Service/StockService.php
> +        $article = Shopware()->Models()->getRepository(\Shopware\Models\Article\Detail::class)->findOneBy(['number' => $number]);
Replace Shopware()->Models() with 'models' service passed through the constructor

2019-02-07 08:08 UTC, uehler commented on engine/Shopware/Bundle/OrderBundle/Service/StockService.php
> +            $oldArticle = $this->getArticleByNumber($oldArticleNumber);
and article should be product ;)

2019-02-07 09:22 UTC, Fredwak commented on engine/Shopware/Bundle/OrderBundle/Service/StockService.php
> +            $oldArticle = $this->getArticleByNumber($oldArticleNumber);
> and article should be product ;)

what do you mean?
Shopware use the word 'article' not 'product' for its products

2019-02-07 09:23 UTC, Fredwak commented on engine/Shopware/Bundle/OrderBundle/Service/StockService.php
> +            Shopware()->Models()->persist($article);
yeah - you are right!
in the past this caller subscriber was a doctrine subscriber. An this would break when you add the DI to the constructor
-> Done (Y)

2019-02-07 09:23 UTC, uehler commented on engine/Shopware/Bundle/OrderBundle/Service/StockService.php
> +            $oldArticle = $this->getArticleByNumber($oldArticleNumber);
they use product in new code, article is just legacy

2019-02-07 09:30 UTC, Fredwak commented on engine/Shopware/Bundle/OrderBundle/Service/StockService.php
> +            $oldArticle = $this->getArticleByNumber($oldArticleNumber);
so i must replace any "article" through "product"? (in any changed files)

2019-02-07 13:28 UTC, rommelfreddy approved these changes

2019-02-07 14:33 UTC, merged

2019-02-07 15:14 UTC, Fredwak commented
I have created a new pull request https://github.com/shopware/shopware/pull/2014 cause there are some issues in the source repo.