Make customergroup keys longer
shopware5/shopware pull request #2031
Opened 2019-02-21 13:01 UTC by pascalheidman-bedarf

### 1. Why is this change necessary?
The customergroup model allows up to 5 chars while the customer model allows 15 characters for the customer group. The lower limit makes naming customer groups hard where you have several similar group names, eg. if you have companies as your customers where each company has their own customergroup. Having more space to use improves it a lot.

### 2. What does this change do, exactly?
Upping the customergroup model's limit to match the limit set in the customer model to 15 characters.

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).

### 5. Which documentation changes (if any) need to be made because of this PR?

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2019-02-21 13:04 UTC, shyim requested changes

2019-02-21 13:04 UTC, shyim commented on _sql/migrations/1607-allow-longer-customergroup-keys.php
> +    public function down($modus): void
Plugin Migrations need only down

2019-02-22 08:14 UTC, PaddyS commented
Whoops. Wrong order.
Anyway, please still fix this issue. :-)

2019-02-22 13:14 UTC, pascalheidman-bedarf commented
@shopwareBot @PaddyS good point.

But: searching through all models I only found references for `$customerGroupKey` in `\Shopware\Models\Article\Configurator\Template\Price::$customerGroupKey` and \Shopware\Models\Article\Price::$customerGroupKey` - both where with a space of 30 characters. Reducing this to match the others limit of 15 characters feels bad as this means potential (but unrealistic) data loss.

Searching further with broader `$customerGroup` revealed an even longer version: `Shopware\Models\Newsletter\Newsletter::$customerGroup` with 255 characters.
Gladly other instances only had a reference for the customergroup id (typical `int(11)`).

What is your suggestion regarding this discrepancy of those fields? As we don't use the newsletter module I don't have data for that usecase anyway but I would feel okay going up to 30 characters but 255 seem overkill.

2019-02-26 11:47 UTC, pascalheidman-bedarf commented
@shopwareBot all right.
I changed all Doctrine annotations to 15 characters but didn't include a migration for those models that had space for more characters (to prevent potential data loss if other changed those fields by hand)

2019-02-26 12:11 UTC, shyim commented
Users can't loose data. The groupkey is defined in s_core_customergroups and the users can't have longer text as there, cause its joined in multiple places

2019-03-05 13:12 UTC, closed without merging

2019-03-05 13:13 UTC, shyim commented
Thanks for your Contribution :blue_heart: