Improve service instantiation & use Doctrine DBAL instead of Zend DB in CacheManager
shopware5/shopware pull request #2190
Opened 2019-09-04 13:18 UTC by pascalheidmann-bedarf

### 1. Why is this change necessary?
Several services are instantiated with parameter "service_container" which can basically be any `Container` that implements the `ContainerInterface` - therefore lots of service classes typehint to narrow with just `Container`.
Then there are several instances where the container is passed to the constructor to load other services. These cases can be simplified a lot.

### 2. What does this change do, exactly?
- Replace all typehints of `Container` with the interface `ContainerInterface` if possible.
- Instantiate services with their required services directly instead of going the route of loading them manually via container
  - if possible remove container completely from services 
- As a bonus I updated the CacheManager to use the `dbal_connection` service instead of `db`.

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).

### 5. Which documentation changes (if any) need to be made because of this PR?
The PR changes the factory method signature of `Shopware\Components\DependencyInjection\Bridge\Plugin::factory`

### 6. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2019-09-04 15:27 UTC, uehler commented on engine/Shopware/Components/CacheManager.php
>          $this->container = $container;
You can pass the parameters like `shopware.httpCache.enabled` via constructor too and can get rid of the container injection

2019-09-04 15:29 UTC, pascalheidmann-bedarf commented on engine/Shopware/Components/CacheManager.php
>          $this->container = $container;
Yeah I know but wasn't sure as there already too many parameters 😅

2019-09-05 07:02 UTC, mitelg commented on engine/Shopware/Components/CacheManager.php
>          $this->container = $container;
I think, better many explicit parameters as one container parameter :wink:

2019-09-05 07:03 UTC, mitelg commented on engine/Shopware/Components/CacheManager.php
>          $this->container = $container;
you could try to inject `shopware.httpCache` afaik you will get an array, so you don't need `shopware.httpCache.enabled`, `shopware.httpCache.cache_dir`, etc

2019-09-05 08:51 UTC, pascalheidmann-bedarf commented
As suggested by @uehler and @mitelg I now inject all parameters (as arrays if possible) into CacheManager and removed the container completely.

2019-09-05 09:23 UTC, mitelg commented on engine/Shopware/Components/CacheManager.php
> +    public function clearHttpCache(): void
you should not change the method signature of public methods by adding typehints and return types. this will be a breaking change

2019-09-05 11:22 UTC, mitelg commented on engine/Shopware/Components/CacheManager.php
> -     * @return array
do not delete return doc

2019-09-05 11:22 UTC, mitelg commented on engine/Shopware/Components/CacheManager.php
> -     * @return array
do not delete return doc

2019-09-05 11:22 UTC, mitelg commented on engine/Shopware/Components/CacheManager.php
> -     * @return array
do not delete return doc

2019-09-05 11:22 UTC, mitelg commented on engine/Shopware/Components/CacheManager.php
> -     * @return array
do not delete return doc

2019-09-05 11:22 UTC, mitelg commented on engine/Shopware/Components/CacheManager.php
> -     * @return array
do not delete return doc

2019-09-05 11:22 UTC, mitelg commented on engine/Shopware/Components/CacheManager.php
> -     * @return array
do not delete return doc

2019-09-05 11:22 UTC, mitelg commented on engine/Shopware/Components/CacheManager.php
> -     * @return string
do not delete return doc

2019-09-05 11:22 UTC, mitelg commented on engine/Shopware/Components/CacheManager.php
> -     * @return int
do not delete return doc

2019-09-05 11:22 UTC, mitelg commented on engine/Shopware/Components/CacheManager.php
> -     * @return bool
do not delete return doc

2019-09-10 07:39 UTC, soebbing commented on engine/Shopware/Components/CacheManager.php
> +    private function clearDirectory($dir): void
You can add a string type here.

2019-09-10 07:44 UTC, soebbing requested changes
Nice PR!

2019-09-10 07:44 UTC, soebbing commented on engine/Shopware/Components/CacheManager.php
>          } else {
You can get rid of the `else` block here by simply initializing the variable `$info = [];` above the `if` condition. The same for the `backend` below.

2019-09-10 07:44 UTC, soebbing commented on engine/Shopware/Components/CacheManager.php
> +    private function clearDirectory($dir): void
Please a string type here.

2019-09-10 10:00 UTC, pascalheidmann-bedarf commented
@soebbing thx!
Because I was already changing more than signatures I added some deprecations for private methods and also removed indirect calls for `cache` service via `cacheManager` by replacing those with explicit service calls in the `Shopware\Components\Api\Resource\Cache` and cache backend controller.

Also I had to fix two return annotations in `\Shopware_Bootstrap` as those seem to be broken/detected now by PHPStan...

2019-09-10 12:00 UTC, mitelg commented on engine/Library/Enlight/Components/Snippet/Manager.php
> +        parent::__construct();
are you sure, that this will not break anything?

2019-09-10 12:02 UTC, mitelg commented on engine/Shopware/Components/CacheManager.php
> +     * @deprecated in 5.7, will be removed in 5.8
you should describe an alternative for this call

2019-09-10 12:03 UTC, mitelg commented on engine/Shopware/Components/CacheManager.php
> +     * @deprecated in 5.7, will be private in 5.8
alternative

2019-09-10 12:03 UTC, mitelg commented on engine/Shopware/Components/CacheManager.php
> +     * @deprecated in 5.7, will be private in 5.8
alternative

2019-09-10 12:21 UTC, pascalheidmann-bedarf commented on engine/Shopware/Components/CacheManager.php
> +     * @deprecated in 5.7, will be private in 5.8
This is a helper that is used only inside the class itself. I don't see any reason for an alternative, especially as this little formatter is just shy 4 lines of code. If a dev needs it somewhere they should better implement it themselves.
Only possible alternative would be moving it into a completely new helper service that wouldn't really fit anywhere.

2019-09-10 12:22 UTC, pascalheidmann-bedarf commented on engine/Shopware/Components/CacheManager.php
> +     * @deprecated in 5.7, will be private in 5.8
I can't have any useful alternative but also see no reason for having this public. Right now the function is used just inside the class itself.

2019-09-10 12:35 UTC, pascalheidmann-bedarf commented on engine/Library/Enlight/Components/Snippet/Manager.php
> +        parent::__construct();
`\Enlight_Components_Snippet_Manager` has only the abstract class `\Enlight_Class` as its ancestor - therefore only the branch `if (method_exists($this, 'init'))` might ever get executed.
So, yes, as long as no dev tries to extend `\Shopware_Components_Snippet_Manager` or `\Enlight_Components_Snippet_Manager` and adds an `init` method this won't have unwanted side-effects.

2019-09-10 12:52 UTC, mitelg commented on engine/Shopware/Components/CacheManager.php
> +     * @deprecated in 5.7, will be private in 5.8
ah ok. then you should add this as info :wink: because it is not used in Shopware itself somewhere else, does not mean, some plugins don't use it :blush:

2019-09-10 12:55 UTC, mitelg commented on engine/Shopware/Components/CacheManager.php
> +     * @deprecated in 5.7, will be private in 5.8
totally have overseen the private hint :smile: forget what i've said

2019-09-11 06:51 UTC, soebbing requested changes
This PR by now isn't about Zend DB alone, but a whole lot more generic. I think you should split your PR into multiple commits, so we can test and modify these changes more atomically.

2019-09-11 06:51 UTC, soebbing commented on engine/Shopware/Components/Api/Resource/Cache.php
> +     *
Please remove these Exception annotations.

The rule Shopware follows with regards to annotating Exceptions is: We only declare them when they are thrown in this method explicitly.
The reasoning for this is as follows: If I modify a function and want to declare all implicit Exceptions as well, it would be necessary to check all functions I am using in my modified function for possible exceptions (your IDE helps you there), but I would also need to change all method annotations for every method calling the modified one, since they would have to get the new exception annotation as well. And that is nearly impossible.

2019-09-11 06:51 UTC, soebbing commented on engine/Shopware/Components/Api/Resource/Cache.php
> +     * @throws \Zend_Cache_Exception
Please see the comment above

2019-09-11 06:51 UTC, soebbing commented on engine/Shopware/Components/Snippet/Manager.php
> +        parent::__construct(new DbAdapter([
My Spidy-Developer senses are tingeling. Why did you change this? I don't see `$this->adapter` being defined anywhere, but it is used later on.

2019-09-11 06:51 UTC, soebbing commented on engine/Shopware/Components/Api/Resource/Cache.php
> +     * @throws ParameterMissingException
See comment below

2019-09-11 06:58 UTC, mitelg commented on engine/Shopware/Components/Snippet/Manager.php
> +        parent::__construct(new DbAdapter([
@soebbing see here. the parent has some "nice" possibilities of parameters in its constructor :smile: https://github.com/shopware/shopware/blob/5.6/engine/Library/Enlight/Components/Snippet/Manager.php#L63

2019-09-11 07:03 UTC, soebbing commented on engine/Shopware/Components/Snippet/Manager.php
> +        parent::__construct(new DbAdapter([
Ok, I wish I wouldn't have seen that. 🤢 But I guess the change is ok then, technically!

2019-09-11 07:38 UTC, pascalheidmann-bedarf commented on engine/Shopware/Components/Snippet/Manager.php
> +        parent::__construct(new DbAdapter([
@soebbing me neither. The main reason I stumbled upon this in the first was my IDE freaking out of missing parent constructor calls. I might add a comment to clarify this.

2019-09-11 09:03 UTC, pascalheidmann-bedarf commented
While splitting all changes into their own commits I realised that the changes regarding SnippetManager aren't really part of the rest and therefore I moved them into #2195

2019-10-07 08:27 UTC, shyim commented
Wrong pull request number :man_facepalming:

2019-10-07 12:52 UTC, shyim commented
When I clear the cache I get following error message
"Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'routerlastupdate' in 'where clause' in /var/www/html/shopware/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:912 Stack trace: #0 /var/www/html/shopware/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(912): PDO->query('SELECT v.shop_i...') #1"

Please test your change before submitting your Pull Request :blush:

2019-10-07 13:10 UTC, mitelg commented on engine/Shopware/Components/DependencyInjection/Bridge/Plugins.php
> +        \Enlight_Loader $loader, \Enlight_Event_EventManager $eventManager, \Shopware $application, array $pluginDirectories, ConfigReader $configReader
please use multi lines here

2019-10-08 07:59 UTC, shyim commented
@pascalheidmann-bedarf Can i lookup? Maybe add next time new commits instead squashing, i can't see the difference

2019-10-10 15:48 UTC, pascalheidmann-bedarf commented
@shopwareBot I rebased to latest version and merged the conflicting changes in `\Shopware_Components_Translation`.
@shyim the mentioned problem happened cause I thought `Expr\Like` would escape... Added the explicit escaping. Next time I will definitely use more commits ;)

2019-10-11 07:07 UTC, shyim commented
Next time please test your PR before submitting it. It was just clearing cache :see_no_evil:

2019-11-25 12:18 UTC, pascalheidmann-bedarf commented
@shopwareBot pls use my private account @pascalheidmann for credits

2019-12-06 09:02 UTC, shyim commented
Thanks for your Contribution! :blue_heart:

2019-12-06 09:02 UTC, closed without merging