Add interfaces for services in AttributeBundle
shopware5/shopware pull request #2222
Opened 2019-09-30 21:26 UTC by jkrzefski

### 1. Why is this change necessary?
Every service in the dependency injection container deserves to have an interface. It enables third party developers to decorate these services with ease.

### 2. What does this change do, exactly?
It adds new interfaces for the services in the AttributeBundle with all the public methods signatures those services already implement.

### 3. Describe each step to reproduce the issue or behaviour.
![](https://i.imgflip.com/3c05t3.jpg)

### 4. Please link to the relevant issues (if any).
None.

### 5. Which documentation changes (if any) need to be made because of this PR?
None.

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2019-09-30 21:30 UTC, shyim requested changes

2019-09-30 21:30 UTC, shyim commented on engine/Shopware/Bundle/AttributeBundle/Service/CrudServiceInterface.php
> +     * @param string $column
please move also the phpdocs

2019-10-01 05:47 UTC, mitelg commented
thanks for your PR @jkrzefski 
you also have to change the typehints in classes, where these classes are used. otherwise the interfaces will have no effect :wink:

2019-10-01 12:18 UTC, jkrzefski commented
@mitelg Yes, I will do that.

2019-10-01 12:18 UTC, jkrzefski commented on engine/Shopware/Bundle/AttributeBundle/Service/CrudServiceInterface.php
> +     * @param string $column
Can you explain, what exactly do you mean?

2019-10-01 12:21 UTC, jkrzefski commented
Btw: I left out the `@throws` statements of the phpdocs on purpose in the interfaces. The reason for me to not have those in the interfaces is, that I believe they are specific to the implementation. Do you approve this?

2019-10-01 12:35 UTC, mitelg commented
@jkrzefski I would say it depends :wink: 
Some interfaces could describe certain throw tags, as the caller of the service will handle them for example. But I don't think that this is the case here

2019-10-01 12:38 UTC, jkrzefski commented
@mitelg Ok, then I'll keep it this way. Should I change the phpdocs of the implementations to `{@inheritdoc}`?

2019-10-03 12:59 UTC, shyim commented on engine/Shopware/Bundle/AttributeBundle/Service/CrudService.php
> +    const EXT_JS_PREFIX = CrudServiceInterface::EXT_JS_PREFIX;
Is this really necessary when the implemented interface contains that?
https://3v4l.org/rotPu

2019-10-03 13:01 UTC, jkrzefski commented on engine/Shopware/Bundle/AttributeBundle/Service/CrudService.php
> +    const EXT_JS_PREFIX = CrudServiceInterface::EXT_JS_PREFIX;
Thank you. I did not think about this. I'll remove it.

2019-10-04 05:50 UTC, mitelg commented on engine/Shopware/Bundle/AttributeBundle/Service/TypeMapping.php
> +    const TYPE_STRING = TypeMappingInterface::TYPE_STRING;
why the duplication?

2019-10-04 06:23 UTC, shyim commented on engine/Shopware/Bundle/AttributeBundle/Service/TypeMapping.php
> +    const TYPE_STRING = TypeMappingInterface::TYPE_STRING;
https://github.com/shopware/shopware/pull/2222#discussion_r331024163

2019-10-10 14:52 UTC, closed without merging

2019-10-10 14:53 UTC, shyim commented
Thanks for your Contribution! :blue_heart: