Filter orders by any payment
shopware5/shopware pull request #2259
Opened 2019-11-15 12:26 UTC by JoshuaBehrens

### 1. Why is this change necessary?
Orders can be placed in the past using a nowadays inactive payment. But you can't filter these orders by them.

### 2. What does this change do, exactly?
It allows to retrieve all payments from the server side, but the ExtJs store always send the same filter that has been applied by the server at first. Then this filter gets overwritten for this specific store to allow choosing inactive payments as well. The order is kept the same as inactive payments are just added below the active ones. It shouldn't be breaking as the store is working the same like before.

### 3. Describe each step to reproduce the issue or behaviour.
1. A payment fails to work properly
2. Payment gets disabled so no further orders using this payment get created
3. Now all failed orders have to be manually processed
4. Open orders
5. Set payment filter to (now inactive) faulty payment
6. You can't do step 5 without this pull request :anger: 

### 4. Which documentation changes (if any) need to be made because of this PR?
The store change has to be part of an UPGRADE file I assume as if anyone uses the exact endpoint manually it has a different outcome (for now).

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2019-11-15 17:39 UTC, shyim requested changes

2019-11-15 17:39 UTC, shyim commented on engine/Shopware/Controllers/Backend/Base.php
> +        $query = $repository->getAllPaymentsQuery(
BC make maybe create new action in order controller

2019-11-16 00:01 UTC, JoshuaBehrens commented on engine/Shopware/Controllers/Backend/Base.php
> +        $query = $repository->getAllPaymentsQuery(
That is right out dirty to create an action that lists all although the action of concern has a documentation that reads like it does not care about any payment property.

I found a less breaking solution. Please comment on that as well

2019-12-05 08:32 UTC, shyim commented
Thanks for your Contribution! :blue_heart:

2019-12-05 08:32 UTC, closed without merging