Introduce Argon2 as new password encoder
shopware5/shopware pull request #2260
Opened 2019-11-15 16:01 UTC by pascalheidmann-bedarf

### 1. Why is this change necessary?
Security

### 2. What does this change do, exactly?
Add new encoders Argon2i and Argon2id.

While `argon2` is considered more secure than `bcrypt` I hadn't enabled it by default as this would require several more code changes and is BC breaking.

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).

### 5. Which documentation changes (if any) need to be made because of this PR?
The availability of the new password encoders requires PHP 7.2/7.3 and argon2 enabled.

### 6. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2019-11-15 17:37 UTC, shyim requested changes

2019-11-15 17:37 UTC, shyim commented on _sql/migrations/1655-add-argon2-hashing.php
> +            'Ein höherer Speicherverbrauch macht es einem möglichen Angreifer schwerer, ein passendes Klartext-Passwort zu erzeugen.',
Translation?

2019-11-16 16:33 UTC, hlohaus commented on engine/Shopware/Components/Password/Encoder/Argon2i.php
> +        return PHP_VERSION_ID >= 70200 && defined('PASSWORD_ARGON2I');
maybe only defined('PASSWORD_ARGON2I')

2019-11-18 13:08 UTC, pascalheidmann-bedarf commented on _sql/migrations/1655-add-argon2-hashing.php
> +            'Higher memory usage increases the security against attackers.',
This sounds not very future proof/i18n ready as AFAIK those values will be used if no translation is present. Therefore users that eg. have a Spanish Shopware installation will be presented with the german translation - which they potentially have more troubles with than with english...

2019-11-18 13:12 UTC, pascalheidmann-bedarf commented
@shopwareBot why 5.7? This isn't breaking anything and 5.7 won't be out soon I guess?
I originally had this for `\Shopware\Components\Password\Manager::getDefaultEncoderName()`:
```php
foreach ($this->encoder as $encoder) {
                if (method_exists($encoder, 'isCompatible') && $encoder->isCompatible()) {
                    return $encoder->getName();
                }
            }
            $encoderName = 'sha256';
```
which would definitely break things but otherwise this is just an enhancement...

2019-11-18 13:27 UTC, pascalheidmann-bedarf commented on engine/Shopware/Plugins/Default/Core/PasswordEncoder/Bootstrap.php
> +     * @return Manager
This would break the signature of an already known function

2019-11-18 13:34 UTC, soebbing commented on tests/Unit/Components/Password/Encoder/Argon2iTest.php
> +     */
I think you can drop this comment and the ones below.

2019-11-19 12:29 UTC, PaddyS commented on engine/Shopware/Plugins/Default/Core/PasswordEncoder/Bootstrap.php
> +     * @return Manager
Since we're in the scope of a plugin here, this method couldn't be overridden anyway and thus doesn't break - does it?

2019-11-19 12:59 UTC, mitelg commented on engine/Shopware/Plugins/Default/Core/PasswordEncoder/Bootstrap.php
> +     * @return Manager
@PaddyS I think you are wrong here :blush: as this is a plugin based on the legacy plugin system, the bootstrap methods should be hookable. and because of that, there are extendable by plugins (theoretically :smile: )

but adding a return type should not break a hook. but I'm not sure about that

2019-11-19 13:01 UTC, shyim commented on engine/Shopware/Plugins/Default/Core/PasswordEncoder/Bootstrap.php
> +     * @return Manager
Plugins are not hookable

2019-11-25 09:52 UTC, pascalheidmann-bedarf commented on engine/Shopware/Plugins/Default/Core/PasswordEncoder/Bootstrap.php
> +     * @return Manager
I added typehints for the plugin's bootstrap file for all functions that aren't inherited. Hope that satisfy your kinks ;)

2019-11-25 12:17 UTC, pascalheidmann-bedarf commented
@shopwareBot pls use my private account @pascalheidmann for credits

2019-12-02 15:44 UTC, shyim commented
Hey,
I tested your PR and my shop is broken when I enable Aragon2i. The registration page just reloads.
Also, all configuration options are missing.

Did you tested your changes?

2019-12-03 10:37 UTC, pascalheidmann commented
@shyim tested kind of 🙈 Not the migration itself again after rewrote which then had problems with `sprintf` and `%d` specifier. Should be now fixed.

2019-12-04 12:46 UTC, pascalheidmann commented
@shopwareBot I tested it on my local installation where the config options now have been applied to the correct form. Also the registration worked as expected. Therefore I consider it tested now, with both manual as well as automated tests ;)

2019-12-05 08:58 UTC, shyim commented
Thanks for your Contribution! :blue_heart:

2019-12-05 08:58 UTC, closed without merging