extract specific Media-Business-Logic to service
shopware5/shopware pull request #2267
Opened 2019-11-21 22:21 UTC by tinect

### 1. Why is this change necessary?
Currently, there is no possibility to modify getThumbnailFilePaths of MediaModel.

### 2. What does this change do, exactly?
This PR:
- extracts some methods to new MediaModelService
- use same methods in MediaModel and MediaManager
- retains current methods to keep not-breaking-change

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).

### 5. Which documentation changes (if any) need to be made because of this PR?

### 6. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2019-11-21 22:22 UTC, tinect commented
@shyim could you please check, if getUploadDir can be removed clearly? :-) Thaaaank you!

2019-11-25 16:09 UTC, pascalheidmann requested changes

2019-11-25 16:09 UTC, pascalheidmann commented on engine/Shopware/Bundle/MediaBundle/MediaModelService.php
> +        $projectDir = Shopware()->Container()->getParameter('shopware.app.rootdir');
Use DI for parameter pls

2019-11-25 16:09 UTC, pascalheidmann commented on engine/Shopware/Bundle/MediaBundle/MediaModelService.php
> +        $mediaService = Shopware()->Container()->get('shopware_media.media_service');
Use DI instead

2019-11-25 16:09 UTC, pascalheidmann commented on engine/Shopware/Bundle/MediaBundle/MediaModelService.php
> +            $path = str_replace(Shopware()->DocPath(), '', $path);
Isn't there some replacement (DI?)

2019-11-25 16:28 UTC, tinect commented
Thank you @pascalheidmann. Noticed this.
Will fix this these days. This is still POC.

2019-11-25 16:43 UTC, shyim commented on engine/Shopware/Bundle/MediaBundle/MediaModelService.php
> +    public function getThumbnailFilePaths(Media $media, $highDpi = false): array
```suggestion
    public function getThumbnailFilePaths(Media $media, bool $highDpi = false): array
```

2019-11-25 16:45 UTC, shyim commented on engine/Shopware/Bundle/MediaBundle/MediaModelService.php
> +        return $projectDir . 'media' . DIRECTORY_SEPARATOR . strtolower($type) . DIRECTORY_SEPARATOR;
$projectDir is not necessary

2019-11-25 16:45 UTC, shyim commented on engine/Shopware/Bundle/MediaBundle/MediaModelService.php
> +    public function getUploadDir($type): string
```suggestion
    public function getUploadDir(string $type): string
```

2019-11-25 16:46 UTC, shyim commented on engine/Shopware/Controllers/Backend/MediaManager.php
> +            $this->mediaModelService = Shopware()->Container()->get('Shopware\Bundle\MediaBundle\MediaModelServiceInterface');
```suggestion
            $this->mediaModelService = Shopware()->Container()->get(\Shopware\Bundle\MediaBundle\MediaModelServiceInterface::class);
```

2019-11-25 16:47 UTC, shyim commented on engine/Shopware/Bundle/MediaBundle/MediaModelService.php
> +        $sizes = [];
In Backend code we start with '140x140' but in frontend not. Is it still working?

2019-11-25 18:37 UTC, tinect commented on engine/Shopware/Bundle/MediaBundle/MediaModelService.php
> +        $sizes = [];
Good catch! Just looked at the preview be working :-) 140er is created and will be deleted, but not shown in the list.

2019-11-26 12:38 UTC, PaddyS commented
Hey @tinect,

can you please add tests, both for the new `MediaModelService` as well as for the code that used to contain those methods, such as the controller action?

Also, if you're naming it `MediaModelService`, we'd like you to extract *all* of the model's private methods to this service, otherwise we'll be left with a weird mix of both.

Additional to that (Sorry! 🙈) it would be cool to move the `onSave` method of the `Media` model to the `ModelSubscriber`, since it already comes with a `PrePersist` listener.

2019-11-27 07:30 UTC, mitelg commented on engine/Shopware/Bundle/MediaBundle/MediaModelServiceInterface.php
> +interface MediaModelServiceInterface
that are a lot of methods :blush: 
maybe we could split this up into different services, like all thumbnail related things, all upload related things, etc

2019-12-04 12:27 UTC, closed without merging