Add sw:admin:login for instant backend login
shopware5/shopware pull request #2283
Opened 2019-12-06 18:05 UTC by jkrzefski

### 1. Why is this change necessary?
It is not necessary. This is merely for convenience.

### 2. What does this change do, exactly?
A new command is introduced to the CLI: `sw:admin:login`
It generates a one-time-password for a backend user that is valid for 30 seconds. The username and the generated password are composed into a url to the backend login controller.

### 3. Describe each step to reproduce the issue or behaviour.
1. Run `sw:admin:login` in CLI.
2. Open the link.
3. You are now logged into the backend 🚀 

### 4. Please link to the relevant issues (if any).
None.

### 5. Which documentation changes (if any) need to be made because of this PR?
I don't know.

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2019-12-06 18:07 UTC, shyim commented on engine/Shopware/Commands/AdminLoginCommand.php
> +        $this->shopRegistrationService->registerResources($shop);
why do we need that?

2019-12-06 18:08 UTC, jkrzefski commented on engine/Shopware/Commands/AdminLoginCommand.php
> +        $this->shopRegistrationService->registerResources($shop);
I generate a url to the backend. If I do not do this, the host of the url would be `localhost`.

2019-12-06 20:46 UTC, hlohaus requested changes

2019-12-06 20:46 UTC, hlohaus commented on engine/Shopware/Commands/AdminLoginCommand.php
> +        $this->shopRegistrationService->registerResources($shop);
you can do $router->getContext()->fromRequest

2019-12-07 13:19 UTC, jkrzefski commented on engine/Shopware/Commands/AdminLoginCommand.php
> +        $this->shopRegistrationService->registerResources($shop);
Done.

2019-12-07 15:00 UTC, shyim commented on engine/Shopware/Commands/AdminLoginCommand.php
> +            $otp = bin2hex(random_bytes(32));
Maybe use https://github.com/shopware/shopware/blob/5.6/engine/Shopware/Components/Random.php#L115

2019-12-08 16:50 UTC, jkrzefski commented on engine/Shopware/Commands/AdminLoginCommand.php
> +            $otp = bin2hex(random_bytes(32));
Done.

2019-12-09 08:57 UTC, uehler commented on engine/Shopware/Commands/AdminLoginCommand.php
> +        $user = $this->modelManager->getRepository(User::class)->findOneBy([
this will return any active backend user but won't there be 1-n users?

2019-12-09 08:59 UTC, uehler commented on engine/Shopware/Commands/AdminLoginCommand.php
> +        $user = $this->modelManager->getRepository(User::class)->findOneBy([
so anyone who calls that command will be logged in as the same user. Wouldn't it be better to require to provide a username?

2019-12-09 09:00 UTC, jkrzefski commented on engine/Shopware/Commands/AdminLoginCommand.php
> +        $user = $this->modelManager->getRepository(User::class)->findOneBy([
Yes, this is true. My intention was to login with the first active backend user that is found. If you would rather have the username as an argument, I can do that too. In that case, I'd keep the current line as fallback, in case no username is given.

2019-12-09 09:10 UTC, jkrzefski commented on engine/Shopware/Commands/AdminLoginCommand.php
> +        $user = $this->modelManager->getRepository(User::class)->findOneBy([
Or should I pick the first **admin** user, that I find?

2019-12-09 12:54 UTC, jkrzefski commented on engine/Shopware/Commands/AdminLoginCommand.php
> +        $user = $this->modelManager->getRepository(User::class)->findOneBy([
@uehler I added an optional argument for the username now. If no username is provided, the command will find the first admin user in the database.

2019-12-10 16:56 UTC, jkrzefski commented on engine/Shopware/Controllers/Backend/Login.php
> +                'code' => 307,
I made something of a mistake here and it is driving me crazy. I accidentally put `code` into the url-parameters instead of the redirect-options (first argument instead of second) and the login works. This is a normal 302-redirect, so my explanation in the comment above is not correct. Having the code in the parameters leads to a url like this: `backend/index/index/code/307` which is obviously not intended. But if I remove this line, the login will not work anymore. It appears that the session-cookie is lost in redirection then. Can someone take a look at this and tell me if they can reproduce this issue? This issue is not even browser-specific anymore. It simply won't work without this line, but I don't know why.

2020-01-02 12:24 UTC, closed without merging