Fix blog statistic with enabled http cache
shopware5/shopware pull request #2287
Opened 2019-12-10 14:26 UTC by hlohaus

### 1. Why is this change necessary?

blog statistic doesn't work if http cache is enabled.

### 2. What does this change do, exactly?

Move code from controller to statistic plugin.

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).

### 5. Which documentation changes (if any) need to be made because of this PR?

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2019-12-10 14:59 UTC, soebbing requested changes

2019-12-10 14:59 UTC, soebbing commented on engine/Shopware/Plugins/Default/Frontend/Statistics/Bootstrap.php
> +        if (!in_array($blogArticleId, $visitedBlogItems, true)) {
You can turn this into an early return (`if (in_array(...)) `)

2019-12-10 14:59 UTC, soebbing commented on engine/Shopware/Plugins/Default/Frontend/Statistics/Bootstrap.php
> +        $session = $this->get('session');
Move the retrieval of the `session` service down below the early return

2019-12-12 09:34 UTC, shyim commented on engine/Shopware/Plugins/Default/Frontend/Statistics/Bootstrap.php
> +        $blogArticleId = (int) $request->get('blogId');
$request->query->getInt

2019-12-20 11:33 UTC, closed without merging

2019-12-20 11:34 UTC, soebbing commented
Hi @hlohaus, thank you for your contribution!