Fix filter empty Orders
shopware5/shopware pull request #2410
Opened 2021-01-27 08:21 UTC by jalbersdorfer

### 1. Why is this change necessary?
If there are open Orders without Details (Orderlines) - unusual, right - then the Open Orders Overview in Customer Frontend breaks.

### 2. What does this change do, exactly?
Fix filtering out Orders without Details (Orderlines) by delaying the `unset` to after iterating the array.

### 3. Describe each step to reproduce the issue or behaviour.
Produce an Order without any Details (Orderlines) and have a look in the Open Customer Orders Frontend Listing.

### 4. Please link to the relevant issues (if any).
n.a.

### 5. Which documentation changes (if any) need to be made because of this PR?
n.a.

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2021-01-27 08:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware/shopware?pullRequest=2410) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopware/shopware?pullRequest=2410) before we can accept your contribution.<br/><hr/>**Juergen Albersdorfer** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/shopware?pullRequest=2410) it.</sub>

2021-01-29 06:41 UTC, mitelg commented
hey @jalbersdorfer 
thanks for your PR :slightly_smiling_face: :+1: 

why are there orders without details in the first place? Afaik, this should not be possible in a default installation. Shouldn't it prevented, that orders could be created without details?

I think, your PR fixes only symptoms, but not the cause

2021-01-29 07:13 UTC, jalbersdorfer commented
Hi @mitelg
thanks for your quick response.

And es you are right, it should not happen in a default installation.
I observed the behavior in regards to a plugin I'm developing.

The core functionality of the plugin is to combine orders of the same customer within a certain period of time into a single order.
Therefore, I _move_ the Order Details from one to another Order. The original Order Heads get set into a _combined_ state,
so they will not be part any further processing.

The customer on the other Hand has received Order Confirmation E-Mails for the original Orders, and therefore I want them be displayed in the Customer Orders Overview with its correct states and also clearly stated that the original Orders have been merged to another Order.

So that's the root cause is myself. On the other hand, even if it might by default never happen, it is clearly a implementation fault which should be fixed.

I even wanted to first fix this and then talk about changing the behavior to not to remove Orders without details from the List. Which should not be a big thing if it nevertheless should never happen in a default environment.

2021-01-29 07:45 UTC, mitelg commented
thanks for the explanation :+1: 

But if you are the reason behind this misbehaviour by yourself, shouldn't you fix it on your site in your plugin? :slightly_smiling_face: 
I'm okay with adding some events or other extensions points, so you can take care of that problem in your plugin properly. what do you think about that?

2021-01-29 09:18 UTC, jalbersdorfer commented
In my opinion, I'm not the reason for the misbehavior (bug), I just found it and want to fix it - not to work around it.
The extension Point is already there (`Shopware_Modules_Admin_GetOpenOrderData_FilterResult`), but the array passed to this is broken on receive because of the bug I try to fix with this PR. I'm fully aware that what I do is not a default workflow, and I want to achieve my goal with as less impact to the shopware core as possible. But please understand that this is clearly a bug. Even if it is not me causing the function to run that path, it would break nevertheless. It is a bug. It is fully reproduceable by unit test. It should be fixed. While on the other hand, the implementation details of my plugin are open for any discussion.

2021-02-01 08:19 UTC, mitelg commented
hey @jalbersdorfer 

thanks again :slightly_smiling_face: :+1: 

I guess, we can go with your changes. But at least removing of the items should not happen silently. What do you think about some logging here?

I will also make some suggestions regarding your code :wink:

2021-02-01 08:21 UTC, mitelg requested changes
also adding a test would be nice :+1:

2021-02-01 08:21 UTC, mitelg commented on engine/Shopware/Core/sAdmin.php
> +            return false;
return `null` here, so we can add a proper return type hint to the method

2021-02-01 08:21 UTC, mitelg commented on engine/Shopware/Core/sAdmin.php
>      private function processOpenOrderDetails(array $orderValue, array $orders, $orderKey)
```suggestion
    private function processOpenOrderDetails(array $orderValue, array $orders, string $orderKey): ?array
```

2021-02-01 08:21 UTC, mitelg commented on engine/Shopware/Core/sAdmin.php
> +     * @return array|false
```suggestion
```

2021-02-01 08:21 UTC, mitelg commented on engine/Shopware/Core/sAdmin.php
> +            $ret = $this->processOpenOrderDetails($orderValue, $orders, $orderKey);
```suggestion
            $processedOrders = $this->processOpenOrderDetails($orderValue, $orders, $orderKey);
```

2021-02-01 08:21 UTC, mitelg commented on engine/Shopware/Core/sAdmin.php
> +            if ($ret) {
```suggestion
            if ($processedOrders !== null) {
```

2021-02-01 08:21 UTC, mitelg commented on engine/Shopware/Core/sAdmin.php
> +                $orders = $ret;
```suggestion
                $orders = $processedOrders;
```

2021-02-01 10:27 UTC, jalbersdorfer commented
Hi, as you state in your comment

> But at least removing of the items should not happen silently. What do you think about some logging here?

I did not start removing the Empty Order Bodies in the first place. I'm just producing them. The silent removing is the default behavior of the Shopware Core which just has an implementation fault.

I really would like to see the empty Order Heads not getting removed silently, but just kept. 

If you agree, I would change the Implementation to just keep them. - Then most of my changes and of your suggestions would be obsolete.

What do you think?

2021-02-01 12:15 UTC, mitelg commented
okay you are right. we can leave the logging out

2021-04-27 06:55 UTC, shyim commented
Hey,

this PR seems still incomplete due to requested changes. We would like to let it open for another week and close it if we don't get a response from you.

2021-05-10 08:47 UTC, closed without merging