Fix/advanced menu delay
shopware5/shopware pull request #2426
Opened 2021-05-19 20:08 UTC by favor-it

### 1. Why is this change necessary?
The advanced menu hover effect does not work correctly. This pull request faces/solves multiple issues:
- The "Hover delay (ms)", that can be configured in the settings, is not respected on first hover of the navigation bar after loading a page. The advanced menu instantly opens. The delay is respected on following (2nd, 3rd, ...) hovers.
- When moving the cursor downwards moving over the navigation bar, the advanced menu always opens. Even when the cursor leaves the navigation bar in less time than configured as "Hover delay (ms)". This happens when the cursor stays in the area where the advanced menu is about to be displayed. This is an annoying behavior, because the advanced menu covers the first part of the content section - every time a user moves down the cursor from the header to the content section (without the intention to open the menu).
- The performance impact of the used mousemove function on body is bad. This problem has partially been addressed with this contribution: https://github.com/shopware/shopware/pull/2153 https://issues.shopware.com/issues/SW-24297 https://github.com/shopware/shopware/commit/06eb4d0b23548848da0b1ed011aee1790ab67408# But this "fix" broke the hover delay resulting in the issue described above.

### 2. What does this change do, exactly?
This change solves the three issues described above by
- reverting the commit https://github.com/shopware/shopware/commit/06eb4d0b23548848da0b1ed011aee1790ab67408#
- replacing the mousemove listener on the body element with mouseleave listeners only on the relevant elements
- initially calling closeMenu() to fix the first issue (hover delay not working on first hover)

### 3. Describe each step to reproduce the issue or behaviour.
Description under '1. Why is this change necessary?' should contain all information to reproduce the issues.

### 4. Please link to the relevant issues (if any).
N/A

### 5. Which documentation changes (if any) need to be made because of this PR?
N/A

### 6. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2021-05-19 20:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware/shopware?pullRequest=2426) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopware/shopware?pullRequest=2426) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/shopware?pullRequest=2426) it.</sub>

2021-06-10 11:49 UTC, shyim commented
Hey @favor-it ,

Can you push your changes in two commits? First reverting that commit and then applying your fixes?

Thanks! :blue_heart:

2021-06-16 14:44 UTC, favor-it commented
Hey @shyim, I have just updated my pull request accordingly.

2021-06-21 18:41 UTC, xf- commented
Hi,

looks interesting. I wrote the first patch from a modified version used in production. Basically the patch moved the events to better position and nowhere near from the setTimeout or delay.
In my version i use `throttle` from underscore to handle the events and delay to avoid rapid firing the event.

I currently testing your version and looks fine with my patches applied.

2021-09-21 10:40 UTC, xf- commented
@favor-it i noticed touch won't work, maybe i messed up something, but it looks like touch won't open the menu. e.g. Tablet.

Fix for me
```js
                me._on($el, 'touchstart', $.proxy(me.onTouchStart, me, i, $el));
                me._on($el, 'mouseenter touchstart', $.proxy(me.onListItemEnter, me, i, $el));
```

2021-10-12 13:33 UTC, DennisGarding commented
> @favor-it i noticed touch won't work, maybe i messed up something, but it looks like touch won't open the menu. e.g. Tablet.
> 
> Fix for me
> 
> ```js
>                 me._on($el, 'touchstart', $.proxy(me.onTouchStart, me, i, $el));
>                 me._on($el, 'mouseenter touchstart', $.proxy(me.onListItemEnter, me, i, $el));
> ```
@favor-it Can you fix this issue so we can import it?

2021-10-12 13:39 UTC, xf- commented
@swDennis What do you mean exactly?
This is a patch for this patch (not in patch format) and replaces 2 lines.
This version runs for now for 3 weeks live without any issue.

2021-10-12 13:48 UTC, DennisGarding commented
> @swDennis What do you mean exactly? This is a patch for this patch (not in patch format) and replaces 2 lines. This version runs for now for 3 weeks live without any issue.

I mean that favour-it can check the problem and fix it in this pullrequest

2021-10-12 14:14 UTC, xf- commented
Line 159 - add `touchstart` to mouseenter

I have a different version after all, that is the reason i didn't provide a patch file. e.g. i removed all the IE non-sence. Touch devices with IE as browser are uncommon (especially to be a tablet or larger for advanced menu).

_Offtopic
There also more patches in development version.
e.g. is an idea to move the menu into js/json. The issue is lighthouse or recommended amount of DOM elements. An unchanged Demostore is already nearly around 1000 Elements and 1500 shouldn't be passed. With a full menu and not 4 items per list + few standard plugins you can easily bypass the 1500 in a list few or shopping world with an article slider. A;sp new Cookie Banner settings are in source code and maybe used at first page hit, afterwards a lot of DOM elements.
https://web.dev/dom-size/_

2021-10-12 14:33 UTC, favor-it commented
@xf- / @swDennis: I just fixed the issue in an additional commit

2021-10-12 14:54 UTC, xf- commented
@mitelg this should be fine now and also work in responsive mode

2021-10-13 05:49 UTC, mitelg requested changes

2021-10-13 05:49 UTC, mitelg commented on engine/Shopware/Plugins/Default/Frontend/AdvancedMenu/Views/frontend/_public/src/js/jquery.advanced-menu.js
> +        onMouseLeave: function (event) {
also this method is not used anymore, we cannot simply remove it, as it would break for people who would have extended this JS plugin and this method. 

please add it again as empty method

2021-10-13 09:03 UTC, DennisGarding approved these changes

2021-10-13 09:43 UTC, mitelg commented
@favor-it one more last thing to do for you :see_no_evil: 

please sign the CLA, otherwise we cannot use your commits :slightly_smiling_face:

2021-10-13 12:42 UTC, favor-it commented
@mitelg CLA has just been signed

2021-10-19 09:43 UTC, mitelg commented
thanks for your contribution @favor-it   👍🎉💙

don't be confused, we merged it on the next branch, which will be merged back to the main branch in a few days

2021-10-19 09:43 UTC, closed without merging