initServiceMode: lowercase `offlineip` addresses
shopware5/shopware pull request #2428
Opened 2021-06-12 14:03 UTC by leeps

## Make allowed IP addresses in `offlineip` lower-case before comparing to the client's IP address as reported by the web server(s).

This will enhance working with IPv6 addresses, which is sometime reported with uppercase letters by some "whatismyip" sites.
The case-sensitive behavior lead to confusion for at least one of our customers who could not access the frontend in ServiceMode despite entering their IPv6 address into the allow list.

### 1. Why is this change necessary?
IPv6 addresses contain letters, they are therefore sensitive to letter case when comparing strings.
When we want to compare if two IPv6 addresses match, we have to compare them case-insensitive, which is usually done by lower casing them.

### 2. What does this change do, exactly?
This change converts the user-set configuration value for `offlineIp`, which is a string of space-separated IP addresses (IPv4 or IPv6), into lower-case.

### 3. Describe each step to reproduce the issue or behavior.
When entering IPv6 addresses with upper-case letters for the configuration value of `offlineIp`, users connecting from those IP addresses would not be able to bypass ServiceMode and be denied access to the store frontend pages.

### 4. Please link to the relevant issues (if any).
n/a

### 5. Which documentation changes (if any) need to be made because of this PR?
n/a

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

Please notify me if any issues appear in this PR, I'll gladly work to correct them.

2021-06-12 14:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware/shopware?pullRequest=2428) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopware/shopware?pullRequest=2428) before we can accept your contribution.<br/><hr/>**Sebastian Lechte** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/shopware?pullRequest=2428) it.</sub>

2021-06-12 14:49 UTC, shyim requested changes

2021-06-12 14:49 UTC, shyim commented on engine/Shopware/Plugins/Default/Core/Router/Bootstrap.php
> +        if (!empty($config->setOffline) && strpos(strtolower($config->offlineIp), $request->getClientIp()) === false) {
What about using stripos? So I would not matter if the config case is wrong or the actual ip

2021-06-12 15:39 UTC, leeps commented on engine/Shopware/Plugins/Default/Core/Router/Bootstrap.php
> +        if (!empty($config->setOffline) && strpos(strtolower($config->offlineIp), $request->getClientIp()) === false) {
Hey @shyim , thank you for your feedback. You are, of course, absolutely right. I'll change it to `stripos()`!

2021-06-14 13:54 UTC, closed without merging

2021-06-14 13:54 UTC, shyim commented
Thanks for your Contribution! 💙