Uncaught DivisionByZeroError with PHP 8
shopware5/shopware pull request #2432
Opened 2021-07-19 11:13 UTC by christopherholst

### 1. Why is this change necessary?

### 2. What does this change do, exactly?

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).

### 5. Which documentation changes (if any) need to be made because of this PR?

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2021-07-19 11:32 UTC, soebbing commented on themes/Frontend/Bare/frontend/blog/header.tpl
> +    {if $sPerPage != 0}
I think it would be more readable to initialize $pages with 0 and remove the `else` case

2021-07-19 11:38 UTC, christopherholst reviewed
like this @soebbing ?

2021-07-19 12:42 UTC, mitelg commented
@christopherholst please fill out the PR template correctly. It is not there to be ignored. 
especially a description how to reproduce this error

2021-07-19 13:12 UTC, christopherholst commented
done.

2021-07-19 15:25 UTC, mitelg commented
I checked this on PHP 8.0.8 and could not reproduce it :thinking: 

looking at the code, `$sPerPage` could only be `0` if there is a plugin doing things, or the products per page setting in backend was set to `0`, which would be silly :grin:

2021-07-26 11:46 UTC, philipgatzka requested changes
Hi @christopherholst , would you mind moving this change out of the template, for example, into a Controller instead? This could help with testing and also decrease the amount of logic inside the template.

2021-08-19 09:34 UTC, philipgatzka commented
Hello, we're closing this pull request due to inactivity. If this change is still important to you, feel free to open another pull request.

For more information about our contribution guidelines, see https://developers.shopware.com/community/contribution-guideline

2021-08-19 09:34 UTC, closed without merging