Change visibility of createOutputDirectory method
shopware5/shopware pull request #2435
Opened 2021-08-17 15:01 UTC by teiling88

This change is needed, if you want to store your product_exports not in the cache directory.

### 1. Why is this change necessary?
I want to store the product exports outside the cache directory to save them on a nfs volume. Without this change, I have to replace the whole controller - yeah!

### 2. What does this change do, exactly?

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).

### 5. Which documentation changes (if any) need to be made because of this PR?

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

2021-08-19 06:46 UTC, philipgatzka requested changes
Hi @teiling88 , thank you for creating this PR! 😁

2021-08-19 06:46 UTC, philipgatzka commented on engine/Shopware/Controllers/Backend/Export.php
>          $dirName = $this->container->getParameter('kernel.cache_dir');
Would you mind changing this, so that the `$dirName` is initially read from config and the `kernel.cache_dir` is used as a fallback?

2021-08-27 08:06 UTC, teiling88 commented on engine/Shopware/Controllers/Backend/Export.php
>          $dirName = $this->container->getParameter('kernel.cache_dir');
I will do that next week!

2021-09-07 15:05 UTC, teiling88 commented on engine/Shopware/Controllers/Backend/Export.php
>          $dirName = $this->container->getParameter('kernel.cache_dir');
I created a slightly different approach. What do you think about it?

2021-09-08 06:03 UTC, mitelg commented on engine/Shopware/Kernel.php
> +            'kernel.cache_dir.product_export' => $this->getCacheDir().'/productexport',
the places where you replaced the code with your new DI parameter looked like this `$cacheDir .= '/productexport/';`(or similar :wink: )

so I guess
```suggestion
            'kernel.cache_dir.product_export' => $this->getCacheDir().'/productexport/',
```
a slash is missing at the end? :thinking:

2021-09-08 06:03 UTC, mitelg commented on engine/Shopware/Controllers/Backend/Export.php
> +    protected function createOutputDirectory()
I really like your new approach :+1: 

so I guess changing the visibility is not necessary anymore?

2021-09-08 06:03 UTC, mitelg commented on engine/Shopware/Controllers/Backend/Export.php
>          $dirName = $this->container->getParameter('kernel.cache_dir');
nice! just two little questions :blush:

2021-09-08 06:08 UTC, mitelg commented on tests/Functional/Core/sExportTest.php
>          /** @var string $cacheDir */
needs to be removed. PHPStan is complaining :wink:

2021-09-08 06:19 UTC, teiling88 reviewed
Pls let me know if everything is ok so I can squash the commits for you :-)

2021-09-08 06:19 UTC, teiling88 commented on engine/Shopware/Controllers/Backend/Export.php
> +    protected function createOutputDirectory()
Yes of course - is fixed :-)

2021-09-08 06:19 UTC, teiling88 commented on engine/Shopware/Kernel.php
> +            'kernel.cache_dir.product_export' => $this->getCacheDir().'/productexport',
Yes good catch, bad copy and past from me. I developed it in our local docker setup and not directly in this repo 👼🏻

2021-09-08 06:19 UTC, teiling88 commented on tests/Functional/Core/sExportTest.php
>          /** @var string $cacheDir */
fixed

2021-09-08 06:25 UTC, mitelg commented on engine/Shopware/Kernel.php
> +            'kernel.cache_dir.product_export' => $this->getCacheDir().'/productexport',
I guess, the cs-fixer will complain about that :grin: 

```suggestion
            'kernel.cache_dir.product_export' => $this->getCacheDir() . '/productexport/',
```

2021-09-08 06:25 UTC, mitelg commented
one more thing :grin: otherwise it looks good to me :+1:

2021-09-08 06:35 UTC, teiling88 commented
Fixed :-)

2021-09-08 06:41 UTC, mitelg commented
very nice! thank you very much so far :+1:

2021-10-11 11:46 UTC, closed without merging

2021-10-11 11:50 UTC, mitelg commented
thanks for your contribution @teiling88   👍🎉💙

note, that we changed the name of the parameter and made it configurable via the `config.php` 
see: https://github.com/shopware/shopware/commit/54f0b29e3aa7eb8265aebeab5b8f7ee0f76e69d8