Feature/structured data enhancement
shopware5/shopware pull request #2442
Opened 2021-10-11 11:49 UTC by AryaSvitkona

### 1. Why is this change necessary?
Markup seems to be deprecated due to [Google documentation](https://developers.google.com/search/docs/advanced/structured-data/product#microdata). That causes a warning in test tool.

### 2. What does this change do, exactly?
Update markup according to guidelines.

### 3. Describe each step to reproduce the issue or behaviour.
1. Open Markup Check Tool by [Google](https://search.google.com/test/rich-results)
2. Provide product detail URL of a shopware instance
3. Run test 

### 4. Please link to the relevant issues (if any).
no relevant issue

### 5. Which documentation changes (if any) need to be made because of this PR?
no relevant issue

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2021-10-11 11:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware/shopware?pullRequest=2442) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopware/shopware?pullRequest=2442) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/shopware?pullRequest=2442) it.</sub>

2021-10-11 11:54 UTC, mitelg requested changes
- could you please have a look at the conflict? you may need a rebase of your branch :wink: 
- you also need to sign the CLA

2021-10-11 11:54 UTC, mitelg commented on .github/PULL_REQUEST_TEMPLATE.md
> +Markup seems to be deprecated due to [Google documentation](https://developers.google.com/search/docs/advanced/structured-data/product#microdata). That causes a warning in test tool.
please revert the changes in this file. it is used as template and should not contain your specific issue description

2021-10-11 11:55 UTC, mitelg commented
hey @AryaSvitkona 
thanks for your first contribution :slightly_smiling_face: :+1: 

I left some comments for you :wink:

2021-10-11 12:10 UTC, AryaSvitkona commented
Thank you @mitelg 
Was a bit unsettled since this is my first contribution :)

2021-10-12 07:05 UTC, AryaSvitkona commented
Since feature branch was created from "next" branch, this PR will be closed

2021-10-12 07:05 UTC, closed without merging