Fix category sorting on PHP8
shopware5/shopware pull request #2444
Opened 2021-10-12 12:46 UTC by Nevay

### 1. Why is this change necessary?
PHP8 changed the behavior of sort functions, [RFC stable sorting](https://wiki.php.net/rfc/stable_sorting) Illegal comparison functions:
> This works, because PHP currently only checks whether the comparison result is “greater than” or not, and never explicitly distinguishes the “equal” and “smaller than” cases. This breaks down with the approach proposed here, because we now do need to know whether values are equal or not, in order to use the fallback sorting criterion.

### 2. What does this change do, exactly?
Return `-1` instead of `0` if left is smaller than right.

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [X] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

2021-10-12 13:38 UTC, mitelg requested changes

2021-10-12 13:38 UTC, mitelg commented on engine/Shopware/Bundle/StoreFrontBundle/Gateway/DBAL/CategoryGateway.php
> +                return $a['__category_id'] > $b['__category_id'] ? 1 : -1;
we should simply use the space ship operator here
```suggestion
                return $a['__category_id'] <=> $b['__category_id'];
```

2021-10-12 13:38 UTC, mitelg commented on engine/Shopware/Bundle/StoreFrontBundle/Gateway/DBAL/CategoryGateway.php
> +            return $a['__category_position'] > $b['__category_position'] ? 1 : -1;
```suggestion
            return $a['__category_position'] <=> $b['__category_position'];
```

2021-10-12 13:39 UTC, mitelg commented
hey @Nevay 

thanks for your first contribution :+1: 

I left some comments, to even improve the code more :slightly_smiling_face:

2021-10-13 12:28 UTC, mitelg approved these changes

2021-10-19 16:28 UTC, LePrau commented
The failed mysql:8.0 unit test seems to be unrelated.
Is a re-run needed?

2021-10-20 12:09 UTC, mitelg commented
I did a re-run and it works now :slightly_smiling_face:

2021-10-22 08:59 UTC, mitelg commented
thanks for your contribution @Nevay  :+1: :tada: :blue_heart:

don't be confused, we merged it on the next branch, which will be merged back to the main branch in a few days

2021-10-22 08:59 UTC, closed without merging