Avoid PHP8 error if the bucket in ES is null
shopware5/shopware pull request #2446
Opened 2021-10-12 15:48 UTC by xf-

### 1. Why is this change necessary?
Avoid PHP error with v8

### 2. What does this change do, exactly?
\Check if the value is null (array_filter needs an array)

### 3. Describe each step to reproduce the issue or behaviour.
Use ES, have an attribute without a value (my case a checkbox - filterable).

### 6. Checklist
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2021-10-12 15:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/shopware/shopware?pullRequest=2446) <br/>All committers have signed the CLA.

2021-10-13 05:52 UTC, mitelg requested changes
would also be nice, if you manage to add a test for this :slightly_smiling_face:

2021-10-13 05:52 UTC, mitelg commented on engine/Shopware/Bundle/SearchBundleES/FacetHandler/ProductAttributeFacetHandler.php
> +            if ($aggregations[$key]['buckets']) {
```suggestion
            if (\is_array($aggregations[$key]['buckets'])) {
```
instead of an implicit check, we should explicitly check what is expected here

2021-10-13 09:21 UTC, xf- commented on engine/Shopware/Bundle/SearchBundleES/FacetHandler/ProductAttributeFacetHandler.php
> +            if ($aggregations[$key]['buckets']) {
Should work, but from my understanding it can only be `?array` and a simple & fast check should work.

2021-10-13 11:01 UTC, xf- commented
@mitelg any chance to get another php8 fix (plugin manager is broken) into next 5.7.4 release?

2021-10-13 11:25 UTC, mitelg commented
@xf- the broken plugin manager is already fixed and will be part of 5.7.4

2021-10-13 11:31 UTC, xf- commented
@mitelg is there a repo for automatic plugin check. I would love to add a regex check for templates.
https://developers.shopware.com/developers-guide/shopware-5-upgrade-guide-for-developers/#snippets

Some developers are ***** and arguing after a bug report, because of something like this `{s name=foo/bar}` isn't a bug, but it will result in '`foo' / 'bar'` and dividing strings is a bad idea.

I just saw the bug is fixed in plugin manager. I will switch development stage to PHP8 Maybe the sentry will catch something.

Would be nice to have finally a working PHP8 release 10 months into lifecycle and 2 months from PHP8.1 away

2021-10-13 12:28 UTC, mitelg approved these changes

2021-10-20 15:01 UTC, mitelg commented
thanks for your contribution @xf-   👍🎉💙

don't be confused, we merged it on the next branch, which will be merged back to the main branch in a few days

2021-10-20 15:01 UTC, closed without merging