add var sCustomPage to template paths
shopware5/shopware pull request #2452
Opened 2021-10-19 13:46 UTC by resslinger

### 1. Why is this change necessary?
Actually, the data of a shop custom page, like attributes, will not be available in templates, if a template path (1-3) is configured.

### 2. What does this change do, exactly?
This PR assign the var sCustomPage to the included tpls. So this templates have access to the other fields of the custom page, like the attributes.

### 3. Describe each step to reproduce the issue or behaviour.
Add a template path
Add a template var
=> The template has no access to the var sCustomPage

Add this line in this PR
Add a template path
Add a template var
=> The template has access to the var sCustomPage

### 4. Please link to the relevant issues (if any).

### 5. Which documentation changes (if any) need to be made because of this PR?

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2021-10-19 13:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/shopware/shopware?pullRequest=2452) <br/>All committers have signed the CLA.

2021-10-20 12:11 UTC, mitelg requested changes

2021-10-20 12:11 UTC, mitelg commented on engine/Shopware/Controllers/Frontend/Custom.php
> +        $this->View()->assign('sCustomPage', $staticPage);
the exact same thing happens in line 75

what does not work for you? :thinking:

2021-10-20 12:26 UTC, resslinger commented on engine/Shopware/Controllers/Frontend/Custom.php
> +        $this->View()->assign('sCustomPage', $staticPage);
We need the attributes of the called shop page in the included template files. The attributes are not available without this change. So I added the code in line 60, so the included templates have access to the attributes of the shop page.

2021-10-20 12:37 UTC, mitelg commented on engine/Shopware/Controllers/Frontend/Custom.php
> +        $this->View()->assign('sCustomPage', $staticPage);
ah, now I see the problem :slightly_smiling_face: :+1: 

would it still work if we move the assignment to this place and remove it at the end of the method, so we do not have it duplicated?

2021-10-20 12:41 UTC, resslinger commented on engine/Shopware/Controllers/Frontend/Custom.php
> +        $this->View()->assign('sCustomPage', $staticPage);
I will test it and will come back to you asap. :)

2021-10-28 07:31 UTC, mitelg approved these changes

2021-11-09 12:04 UTC, closed without merging

2021-11-09 16:17 UTC, mitelg commented
thanks for your contribution @resslinger  👍🎉💙