refactor: Replace plain sql of getMaxTax by querybuilder and add event
shopware5/shopware pull request #2478
Opened 2022-01-30 14:13 UTC by aragon999

### 1. Why is this change necessary?
Currently there is no way to modify the SQL which is used to retrieve the max tax. In order to extend there a replace hook is needed.

### 2. What does this change do, exactly?
Refactor the plain SQL as query builder and supply this query builder in a new `notify` event: `Shopware_Modules_Basket_GetMaxTax_QueryBuilder`.

### 3. Describe each step to reproduce the issue or behaviour.
\-

### 4. Please link to the relevant issues (if any).
\-

### 5. Which documentation changes (if any) need to be made because of this PR?
\-

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2022-01-30 14:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware/shopware?pullRequest=2478) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopware/shopware?pullRequest=2478) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/shopware?pullRequest=2478) it.</sub>

2022-01-31 09:32 UTC, mitelg requested changes

2022-01-31 09:32 UTC, mitelg commented on engine/Shopware/Core/sBasket.php
> +        if (!$sessionId) {
```suggestion
        if (!is_string($sessionId)) {
```

2022-01-31 09:32 UTC, mitelg commented on engine/Shopware/Core/sBasket.php
> +                'subject' => $this,
please remove the reference to the class. If we want to move the method into an own service, we will get a problem, if we still need to reference the old core class :wink:

2022-01-31 09:32 UTC, mitelg commented on engine/Shopware/Core/sBasket.php
> +        \assert($statement instanceof ResultStatement);
this should not be necessary. also asserts made some troubles in the past :grimacing:

2022-01-31 09:32 UTC, mitelg commented on engine/Shopware/Core/sBasket.php
> +        $maxTaxId = $statement->fetchColumn();
```suggestion
        $maxTaxId = $statement->fetchOne();
```
`fetchColumn` is deprecated

2022-01-31 10:15 UTC, aragon999 commented on engine/Shopware/Core/sBasket.php
> +        \assert($statement instanceof ResultStatement);
I usually have a phpstan error with such things, that is why I added the assert here, since the `execute` method can return an `int`. But actually I noticed that is not very good, how I have done it, since `ResultStatement` does not has the property `fetchOne`, thus the next "issue" with this PR. Since I did not know how to replace `fetchColumn` on an object which does not has `fetchOne`.

TL;DR: I will look into it, but would be happy to get input on how to handle the ambiguous return values.

2022-01-31 10:40 UTC, mitelg commented on engine/Shopware/Core/sBasket.php
> +                $qb->expr()->eq('basket.modus', '0')
```suggestion
                $qb->expr()->eq('basket.modus', \Shopware\Bundle\CartBundle\CartPositionsMode::PRODUCT)
```

2022-01-31 10:43 UTC, mitelg commented on engine/Shopware/Core/sBasket.php
> +        \assert($statement instanceof ResultStatement);
this is a known issue: https://github.com/shopware/shopware/blob/5.7/.phpstan.neon#L92-L93

just omit the `$statement variable` and PHPStorm should auto-complete the right method :slightly_smiling_face:

2022-01-31 10:56 UTC, aragon999 commented on engine/Shopware/Core/sBasket.php
> +        \assert($statement instanceof ResultStatement);
I see, I was not aware that there exists such a thing in the baseline :)

2022-01-31 11:00 UTC, aragon999 commented on engine/Shopware/Core/sBasket.php
> +        \assert($statement instanceof ResultStatement);
Btw. I do not use PHPStorm :) but the language server works as well.

The problem was, that I forgot to run a composer install... and therefore had a too old version of `doctrine/dbal` installed. But now it should be all solved :) Thanks for the feedback.

2022-01-31 12:46 UTC, mitelg approved these changes

2022-02-01 08:52 UTC, closed without merging

2022-02-01 08:56 UTC, PascalThesing commented
Hey @aragon999, 

We just merge your changes.
Thank you for taking the time to create and adapt it! 

Congratulations 🎉