Add event to advanced menu plugin
shopware5/shopware pull request #2492
Opened 2022-04-21 13:54 UTC by larsbo

### 1. Why is this change necessary?

Because there is no good entry point to extend the advanced menu data.

### 2. What does this change do, exactly?

Adds a new event `Shopware_Plugins_AdvancedMenu_ConvertCategory`. 

### 3. Describe each step to reproduce the issue or behaviour.

Try to add thumbnails to media entries and realize there is no simple ways to append the thumbnail details.

### 4. Please link to the relevant issues (if any).

### 5. Which documentation changes (if any) need to be made because of this PR?

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2022-04-21 13:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware/shopware?pullRequest=2492) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopware/shopware?pullRequest=2492) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/shopware?pullRequest=2492) it.</sub>

2022-04-25 07:19 UTC, mitelg commented
hey @larsbo 

your PR looks good so far, but I have some comments :wink:

2022-04-28 15:21 UTC, larsbo commented
@mitelg what comments? 😃

2022-04-28 19:58 UTC, mitelg requested changes

2022-04-28 19:58 UTC, mitelg commented on engine/Shopware/Plugins/Default/Frontend/AdvancedMenu/Bootstrap.php
> +            $eventManager = Shopware()->Container()->get('events');
please move this out of the loop

2022-04-28 19:58 UTC, mitelg commented on engine/Shopware/Plugins/Default/Frontend/AdvancedMenu/Bootstrap.php
> +            $data = $eventManager->filter('Shopware_Plugins_AdvancedMenu_ConvertCategory', $data, [
maybe one event after the loop is enough for your purpose? I don't know if this could have performance impacts, if we start an event for each category

2022-04-28 19:59 UTC, mitelg commented
wow, they were still pending 🤦‍♂️

2022-05-02 19:02 UTC, larsbo commented on engine/Shopware/Plugins/Default/Frontend/AdvancedMenu/Bootstrap.php
> +            $data = $eventManager->filter('Shopware_Plugins_AdvancedMenu_ConvertCategory', $data, [
sure, one event is sufficient.

2022-05-02 19:16 UTC, larsbo commented on engine/Shopware/Plugins/Default/Frontend/AdvancedMenu/Bootstrap.php
> +            $data = $eventManager->filter('Shopware_Plugins_AdvancedMenu_ConvertCategory', $data, [
I think about that, too. But the main reason for an event inside the loop is to reuse the Media instance. If we have just an event after the loop all the (legacy) struct converting stuff has to be done again or you have to query the db again for additional media details that are lost after the loop.

2022-05-03 07:49 UTC, mitelg commented on engine/Shopware/Plugins/Default/Frontend/AdvancedMenu/Bootstrap.php
> +            $data = $eventManager->filter('Shopware_Plugins_AdvancedMenu_ConvertCategory', $data, [
okay, I guess it would be okay. we will see :grin:

2022-05-11 06:38 UTC, mitelg commented
thanks for your contribution @larsbo  👍🎉💙

the changes were pushed on the next branch and will be merged back, as soon we are stable again :wink:

2022-05-11 06:38 UTC, closed without merging