Fix modernizr path in template
shopware5/shopware pull request #2496
Opened 2022-05-10 12:54 UTC by MBDealer

### 1. Why is this change necessary?
The path to the modernizr file is incorrect.

### 2. What does this change do, exactly?
Fixes the path to the modernizr file.

### 3. Describe each step to reproduce the issue or behaviour.
You get a 404 error message in dev tools.

### 4. Please link to the relevant issues (if any).
https://issues.shopware.com/issues/SW-26145

### 5. Which documentation changes (if any) need to be made because of this PR?
-

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2022-05-10 13:51 UTC, mitelg requested changes

2022-05-10 13:51 UTC, mitelg commented on themes/Frontend/Bare/frontend/index/header.tpl
> +        <script src="{preload file={link file='frontend/_public/src/js/vendors/modernizr/modernizr.custom.js'} as="script"}"></script>
the file name has a dash 😉
https://github.com/shopware/shopware/blob/5.7/themes/Frontend/Responsive/frontend/_public/src/js/vendors/modernizr/modernizr-custom.js

2022-05-10 14:12 UTC, MBDealer commented on themes/Frontend/Bare/frontend/index/header.tpl
> +        <script src="{preload file={link file='frontend/_public/src/js/vendors/modernizr/modernizr.custom.js'} as="script"}"></script>
I fixed the typo.

2022-06-07 08:32 UTC, closed without merging

2022-06-07 08:38 UTC, mitelg commented
thanks for your contribution @MBDealer 👍🎉💙