Feature/allow numbers in contenttype names
shopware5/shopware pull request #2511
Opened 2022-10-06 14:18 UTC by bforbird

### 1. Why is this change necessary?
After SW-26513 numbers are no longer allowed in naming of content types

### 2. What does this change do, exactly?
Changes regex to allow numbers.

### 3. Describe each step to reproduce the issue or behaviour.
Create a content type with a number in the name. For example "b2b".

### 4. Please link to the relevant issues (if any).

### 5. Which documentation changes (if any) need to be made because of this PR?

### 6. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfill them.

2022-10-06 14:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware/shopware?pullRequest=2511) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopware/shopware?pullRequest=2511) before we can accept your contribution.<br/><hr/>**Bastiaan de Vogel** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/shopware?pullRequest=2511) it.</sub>

2022-10-07 05:18 UTC, mitelg commented
thanks for your contribution 🙂👍

@xf- does this look okay for you? 😉

2022-10-07 09:38 UTC, mitelg requested changes

2022-10-07 09:38 UTC, mitelg commented on engine/Shopware/Bundle/ContentTypeBundle/Resources/contenttypes.xsd
> +                        <xsd:pattern value="[A-z0-9]+"/>
please ensure, that the name starts with a character. 

names starting with a number can cause problems. 

please ensure this also with a test

2022-10-07 11:02 UTC, bforbird commented on engine/Shopware/Bundle/ContentTypeBundle/Resources/contenttypes.xsd
> +                        <xsd:pattern value="[A-z0-9]+"/>
Hi, I changed it and added a test for it.

2022-10-07 11:05 UTC, xf- commented
@mitelg `*` is a wrong qualifier, allows an empty element. + One or more, * zero or more.

2022-10-07 11:10 UTC, bforbird commented
> 

Hi @xf- , that's right, only for the last section. The first section says the name should always contain 1 letter.
[A-z] -> single character, followed by zero or more [A-z0-9]

2022-10-07 11:17 UTC, xf- commented
> > 
> 
> Hi @xf- , that's right, only for the last section. The first section says the name should always contain 1 letter. [A-z] -> single character, followed by zero or more [A-z0-9]

Saw a different version or overlooked the unchanged non highlighted part. I noticed & edited the comment, while you wrote the last one.

2022-10-07 11:19 UTC, bforbird commented
> > > 
> > 
> > 
> > Hi @xf- , that's right, only for the last section. The first section says the name should always contain 1 letter. [A-z] -> single character, followed by zero or more [A-z0-9]
> 
> Saw a different version or overlooked the unchanged non highlighted part. I noticed & edited the comment, while you wrote the last one.

Ah I see now. :+1: Thanks :wink:

2022-10-07 11:53 UTC, mitelg approved these changes

2022-10-24 15:03 UTC, mitelg commented
thanks for your contribution @bforbird  👍🎉💙

merged with https://github.com/shopware/shopware/commit/2ec8463b880b4a7620c9927adca73c869859fcec
Will be part of 5.7.17

2022-10-24 15:03 UTC, closed without merging