Move deprecation notice to correct service
shopware5/shopware pull request #2512
Opened 2022-10-18 08:53 UTC by larsbo

### 1. Why is this change necessary?
Because the deprecation tag is inside the new service instead of the deprecated one every usage of the right service causes a (wrong) deprecation log entry.

### 2. What does this change do, exactly?
Move the deprecation tag from the new service `shopware_elastic_search.client` to the deprecated service `shopware_elastic_search.client.logger`.

### 3. Describe each step to reproduce the issue or behaviour.
Use Shopware 5 with elastic search and debug log level, open up the article list in the backend and look into the logfile. You will find entries with `The "shopware_elastic_search.client.logger" service is deprecated. Use "shopware_elastic_search.client" instead`.

### 4. Please link to the relevant issues (if any).

### 5. Which documentation changes (if any) need to be made because of this PR?

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

2022-10-18 08:57 UTC, mitelg requested changes

2022-10-18 08:57 UTC, mitelg commented on engine/Shopware/Bundle/ESIndexingBundle/DependencyInjection/services.xml
> +            <deprecated>The "%alias_id%" service is deprecated. Use "%service_id%" instead</deprecated>
shouldn't it be the other way arround? :thinking: 

```suggestion
            <deprecated>The "%service_id%" service is deprecated. Use "%alias_id%" instead</deprecated>
```

2022-10-18 09:06 UTC, larsbo commented on engine/Shopware/Bundle/ESIndexingBundle/DependencyInjection/services.xml
> +            <deprecated>The "%alias_id%" service is deprecated. Use "%service_id%" instead</deprecated>
good point! 😄 
I just copied it from https://github.com/shopware/shopware/blob/67d2985a7f84bd7c5cb55b4efd6af72d0468a975/engine/Shopware/Components/DependencyInjection/api.xml#L104-L115 😉

2022-10-18 09:08 UTC, mitelg commented on engine/Shopware/Bundle/ESIndexingBundle/DependencyInjection/services.xml
> +            <deprecated>The "%alias_id%" service is deprecated. Use "%service_id%" instead</deprecated>
now, I am confused :smile: 

would you mind checking, if the message is now correct? maybe we need to fix the other ones, too? :thinking:

2022-10-18 10:56 UTC, larsbo commented on engine/Shopware/Bundle/ESIndexingBundle/DependencyInjection/services.xml
> +            <deprecated>The "%alias_id%" service is deprecated. Use "%service_id%" instead</deprecated>
The other ones are wrong and I copied it from there. 😸 
`%alias_id%` will output the service name defined in the `alias` attribute of course.
This means the api deprecations currently output
```
shopware.api.customer_stream instead is deprecated, use shopware.api.customer_stream instead
```
I will fix them too. 😉

2022-10-18 14:07 UTC, mitelg approved these changes

2022-10-24 07:42 UTC, mitelg commented
thanks for your contribution @larsbo  👍🎉💙

2022-10-24 07:42 UTC, closed without merging