Update Application.php
shopware5/shopware pull request #2513
Opened 2022-10-27 08:26 UTC by teiling88

### 1. Why is this change necessary?
We (@migo315 and I) run into a strange issue with the shopware update process from 5.6 to 5.7 with php 7.4.23. Not all Commands showed up after the update to 5.7. After the php update process everything worked fine. So we digged deeper cause shopware and php update at once is to risky for us. 

So we found a hot fix to add to all missing Commands the "protected static $defaultName" parameter and then they showed up again. But with this fix we are not happy so we digged deeper. So we created this pull request. This change make it work again for us. It seems, that we run in a rare situation from in_array. See this: https://www.php.net/manual/en/function.in-array.php and our running example with example data:
https://3v4l.org/T9bA8
Without the strict no service is registered. With strict mode: 
https://3v4l.org/9N4HM

We think, through the symfony update  in sw 5.7 we run with our heavily extended shopware installation in a rare php issue with in_array.

"Prior to PHP 8.0.0, a string needle will match an array value of 0 in non-strict mode, and vice versa. That may lead to undesireable results. Similar edge cases exist for other types, as well. If not absolutely certain of the types of values involved, always use the strict flag to avoid unexpected behavior."

What do you think about that?

### 2. What does this change do, exactly?

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).

### 5. Which documentation changes (if any) need to be made because of this PR?

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

2022-10-27 11:24 UTC, mitelg requested changes

2022-10-27 11:24 UTC, mitelg commented on engine/Shopware/Components/Console/Application.php
> +                if (!\in_array($id, $lazyServices, true)) {
after debugging with @shyim the whole method can simplified to this:

```php
    protected function registerTaggedServiceIds()
    {
        if ($this->kernel->getContainer()->hasParameter('console.command.ids')) {
            foreach ($this->kernel->getContainer()->getParameter('console.command.ids') as $id) {
                $this->add($this->kernel->getContainer()->get($id));
            }
        }
    }
```

2022-10-27 13:48 UTC, teiling88 commented on engine/Shopware/Components/Console/Application.php
> +                if (!\in_array($id, $lazyServices, true)) {
Done! :-)

2022-10-27 13:54 UTC, mitelg approved these changes

2022-11-02 07:52 UTC, mitelg commented
merged with [1ce9651](https://github.com/shopware/shopware/commit/1ce96514f6d675fe5bd855f1e7a4dece4fd462d3) and will be part auf 5.7.17

thanks for your contribution @teiling88  👍🎉💙

2022-11-02 07:52 UTC, closed without merging