ci(sw-27129): add danger php
shopware5/shopware pull request #2529
Opened 2023-06-13 14:00 UTC by PascalThesing

### 1. Why is this change necessary?
Currently, all types of commit messages are possible.
We should be strict about this.

### 2. What does this change do, exactly?
This change introduces a check for the commit messages.
These should follow the https://www.conventionalcommits.org/ specification.

2023-06-13 14:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/shopware5/shopware?pullRequest=2529) <br/>All committers have signed the CLA.

2023-06-13 14:07 UTC, mitelg approved these changes

2023-06-13 14:17 UTC, mitelg requested changes

2023-06-13 14:17 UTC, mitelg commented on .danger.php
> +            $context->warning('The Pull Request doesn\'t contain any changelog file');
this message should be adjusted

2023-06-13 14:29 UTC, mitelg approved these changes

2023-06-13 18:32 UTC, mitelg requested changes

2023-06-14 09:06 UTC, mitelg approved these changes

2023-06-19 07:26 UTC, swDennis approved these changes

2023-06-19 07:35 UTC, merged