SW-24582 - Fix swap translations
shopware5/shopware pull request #2535
Opened 2023-06-19 09:59 UTC by swDennis

2023-06-19 09:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware5/shopware?pullRequest=2535) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopware5/shopware?pullRequest=2535) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware5/shopware?pullRequest=2535) it.</sub>

2023-06-20 07:16 UTC, ennasus4sun commented on engine/Shopware/Components/Translation/SwapProductVariantTranslationService.php
> +    public function swapProductVariantTranslation(ProductVariant $newMainVariant, ProductVariant $oldMaiVariant): void
```suggestion
    public function swapProductVariantTranslation(ProductVariant $newMainVariant, ProductVariant $oldMainVariant): void
```

2023-06-20 07:27 UTC, ennasus4sun approved these changes

2023-06-20 08:30 UTC, mitelg approved these changes

2023-06-21 09:31 UTC, mitelg requested changes
please change the target branch to "next"

2023-06-21 12:46 UTC, mitelg commented
rebase to current "next"

2023-06-21 13:28 UTC, rathmerdominik approved these changes

2023-06-26 05:25 UTC, merged

2023-06-26 11:13 UTC, mitelg commented on UPGRADE-5.7.md
> +* Changed behaviour of the translation transfer while setting a product variant as the main variant
@swDennis 
I have overseen this :see_no_evil: 
could you please add a new section for the upcoming 5.7.19 version? because this is for 5.7.18, which will be released soon

2023-06-26 11:49 UTC, mitelg commented on UPGRADE-5.7.md
> +* Changed behaviour of the translation transfer while setting a product variant as the main variant
I will take care :slightly_smiling_face: