fix:(SW-27140) Tests are executed in dependence on each other
shopware5/shopware pull request #2544
Opened 2023-06-27 13:12 UTC by swDennis

2023-06-27 15:54 UTC, aragon999 commented
Just a minor remark, not related to the content of this PR, I guess I would name the commit something like `ci(SW-27140): Execute tests in dependence of each other` :) 

The reasoning behind this tag would be, that `ci` commits can be omitted from changelogs, as they are not really relevant for downstream :-)

2023-06-28 07:22 UTC, mitelg requested changes

2023-06-28 07:22 UTC, mitelg commented on composer.lock
> +            "version": "4.11.0",
please revert this. otherwise PHP7.4 can no longer used

2023-06-28 07:22 UTC, mitelg commented on composer.lock
> +            "version": "4.11.0",
this will probably cause a fail in the pipeline once a PHP7.4 job is executed. at least I hope so :grimacing:

2023-06-28 08:09 UTC, ennasus4sun approved these changes

2023-06-28 08:11 UTC, swDennis commented on composer.lock
> +            "version": "4.11.0",
ohh no.. i forgot to revert it. Thnaks

2023-06-28 11:36 UTC, mitelg commented
looks good so far, but you need a rebase on "next" branch and then resolving the conflicts

2023-06-28 13:54 UTC, aragon999 commented
And the scope of the commit (i.e. the ticket number) should be before the colon :-) 
https://www.conventionalcommits.org/en/v1.0.0/#summary

Not sure why danger did not ran.

2023-07-04 07:01 UTC, mitelg requested changes
needs a rebase due to conflicts

2023-07-04 08:52 UTC, mitelg approved these changes

2023-07-04 09:02 UTC, merged