ci(SW-27133): Cancel previous pipelines
shopware5/shopware pull request #2546
Opened 2023-07-04 07:46 UTC by swDennis

2023-07-04 07:52 UTC, mitelg requested changes
branch needs a rebase. the tests are failing because of a test, that is already fixed

2023-07-04 08:00 UTC, rathmerdominik approved these changes

2023-07-04 08:36 UTC, mitelg approved these changes

2023-07-04 09:05 UTC, mitelg requested changes
needs a rebase again, because the other PR was merged first :grimacing:

2023-07-04 12:38 UTC, mitelg approved these changes

2023-07-04 13:07 UTC, mitelg requested changes

2023-07-04 13:07 UTC, mitelg commented on .github/workflows/check-code.yml
what is this for an empty file?

2023-07-04 13:08 UTC, mitelg requested changes

2023-07-04 13:08 UTC, mitelg commented on .github/workflows/create-release.yml
> +concurrency:
I don't think we need that on create release and create update, as they are only triggered manually or when a tag is pushed

2023-07-04 13:08 UTC, mitelg commented on .github/workflows/create-update.yml
> +concurrency:
see above

2023-07-04 13:09 UTC, mitelg requested changes

2023-07-04 13:09 UTC, mitelg commented on .github/workflows/check-code.yml
I think you wanted to split the JS and PHP part, right? :thinking:

2023-07-04 13:15 UTC, swDennis commented on .github/workflows/check-code.yml
it cames from the rebase to main... there it was recreated

2023-07-04 13:44 UTC, mitelg approved these changes

2023-07-04 14:19 UTC, mitelg approved these changes

2023-07-05 06:26 UTC, ennasus4sun approved these changes

2023-07-05 07:16 UTC, merged