fix(SW-27151): split emails before validation
shopware5/shopware pull request #2549
Opened 2023-07-06 14:49 UTC by ennasus4sun

Separates the transmitted addresses before passing them to the validation.
Otherwise they will always be validated to false.

2023-07-06 15:06 UTC, aragon999 commented
Could it break, for example when one creates a new user, with multiple mails? This was invalid before, but now would become valid:
https://github.com/shopware5/shopware/blob/95e77156a9c8e0f2c3b731d7e4835cb26921c36d/themes/Backend/ExtJs/backend/user_manager/view/user/create.js#L424-L435

2023-07-06 15:13 UTC, mitelg requested changes

2023-07-06 15:13 UTC, mitelg commented on engine/Shopware/Controllers/Backend/Base.php
> +                $this->Response()->setContent(1);
we should set this content only at the end once. if multiple emails are provided, and they are all valid, we would have multiple `1` in the response, which could be misinterpreted

2023-07-06 15:13 UTC, mitelg commented on engine/Shopware/Controllers/Backend/Base.php
> +                break;
instead of a break, we could directly return, because we found some invalid mail already

2023-07-06 15:15 UTC, mitelg commented
@aragon999 it was possible before :thinking: the old email validation was basically "is there an "@" then it is valid" 

so it didn't matter, if the string provided was multiple emails divided with a comma :grin:

2023-07-07 06:20 UTC, mitelg approved these changes

2023-07-07 06:21 UTC, mitelg commented on engine/Shopware/Controllers/Backend/Base.php
> +        $emails = explode(',', $this->Request()->getParam('value', ''));
```suggestion
        $emails = explode(',', (string) $this->Request()->getParam('value', ''));
```

just to make sure, explode gets always a string. I think it would otherwise give some notices on newer PHP versions :thinking:

2023-07-10 07:23 UTC, mitelg approved these changes

2023-07-10 09:17 UTC, swDennis approved these changes

2023-07-10 09:19 UTC, merged