fix doc path
shopware5/shopware pull request #2621
Opened 2023-11-16 10:02 UTC by jschwalmi

Wrong DocPath means that the path or class cannot be downloaded.
![Bildschirmfoto 2023-11-16 um 10 36 22](https://github.com/shopware5/shopware/assets/23236518/f43c102e-a67e-4e0c-bb92-2cd209690a44)
![Bildschirmfoto 2023-11-16 um 10 37 08](https://github.com/shopware5/shopware/assets/23236518/cfad5a86-2c27-479a-8c12-a357f6f3fdfd)

2023-11-16 10:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware5/shopware?pullRequest=2621) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopware5/shopware?pullRequest=2621) before we can accept your contribution.<br/><hr/>**Jana Voits** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware5/shopware?pullRequest=2621) it.</sub>

2023-11-16 13:25 UTC, mitelg commented
hey @jschwalmi 

thanks for your contribution! Good catch indeed :grin: :+1: 

Please make sure, that you commit the changes with your GitHub user and sign the CLA with this user :slightly_smiling_face: 

The commit message should look like described here: https://github.com/shopware5/shopware/wiki/Contribute#commit-message

2023-11-20 11:14 UTC, shyim commented on engine/Shopware/Components/ReflectionHelper.php
> +        $folders[] = Shopware()->DocPath('vendor_shopware5_shopware');
isn't the name computed by the composer package name, and that is still shopware/shopware

2023-11-20 12:28 UTC, mitelg requested changes

2023-11-20 12:28 UTC, mitelg commented on engine/Shopware/Components/ReflectionHelper.php
> +        $folders[] = Shopware()->DocPath('vendor_shopware5_shopware');
@shyim is right. @jschwalmi with your change, the path would look like this: `/home/mt/www/5.7/vendor/shopware5/shopware/`, but that path does not exist. 

Could you explain, how the problem could be reproduced?

2023-11-20 12:47 UTC, jschwalmi commented on engine/Shopware/Components/ReflectionHelper.php
> +        $folders[] = Shopware()->DocPath('vendor_shopware5_shopware');
@mitelg @shyim 
I discovered this problem because it was reported that the product stream with Peudo prices no longer worked. All products were displayed in the stream and not only the discounted products.
In the [\Shopware_Controllers_Backend_ProductStream::loadPreviewAction](https://github.com/shopware5/shopware/blob/15919fda5f13a3b74c870456a3548981c6035da6/engine/Shopware/Controllers/Backend/ProductStream.php#L74) the conditions could not be unserialized. [vendor/shopware5/shopware/engine/Shopware/Controllers/Backend/ProductStream.php:99](https://github.com/shopware5/shopware/blob/15919fda5f13a3b74c870456a3548981c6035da6/engine/Shopware/Controllers/Backend/ProductStream.php#L99).
I think all product streams that have a condition are affected by this.

2023-11-20 12:50 UTC, shyim commented on engine/Shopware/Components/ReflectionHelper.php
> +        $folders[] = Shopware()->DocPath('vendor_shopware5_shopware');
How did you installed Shopware? 🤔

2023-11-20 12:53 UTC, jschwalmi commented on engine/Shopware/Components/ReflectionHelper.php
> +        $folders[] = Shopware()->DocPath('vendor_shopware5_shopware');
@shyim I install Shopware over composer. Do you think that this is not the case in a ZIP installation?

2023-11-20 13:03 UTC, shyim commented on engine/Shopware/Components/ReflectionHelper.php
> +        $folders[] = Shopware()->DocPath('vendor_shopware5_shopware');
```sh
composer create-project shopware/composer-project:@dev test
cd test
ls -la vendor/shopware/shopware
```

seems fine for me 🤔

2023-11-20 15:01 UTC, jschwalmi commented on engine/Shopware/Components/ReflectionHelper.php
> +        $folders[] = Shopware()->DocPath('vendor_shopware5_shopware');
I agree that it could work

2023-12-01 09:01 UTC, mitelg commented
hey @jschwalmi what is the status here? :blush:

2023-12-01 09:06 UTC, jschwalmi commented
> hey @jschwalmi what is the status here? 😊

The comment from @shyim is fine for me  :) 
https://github.com/shopware5/shopware/pull/2621#discussion_r1399177921

2023-12-04 09:14 UTC, mitelg commented
alright, then I will close your PR :slightly_smiling_face: :+1:

2023-12-04 09:14 UTC, closed without merging