fix NotifyAlreadyRegistered is never set caused by fetchColumn
shopware5/shopware pull request #2627
Opened 2024-01-09 13:37 UTC by kayaArvatis

### 1. Why is this change necessary?
`$NotifyAlreadyRegistered` is never set `fetchColumn` is still used but it is an old method and is deprecated with new library version of doctrine. `$ordernumbers` is currently an string but it should be an array since it is iterated.

### 2. What does this change do, exactly?
Fixes the variable `$NotifyAlreadyRegistered` to be set and available in the storefront.

### 3. Describe each step to reproduce the issue or behaviour.
Choose a product that is out of stock and has notification feature enabled:

- Enter an email address
- Confirm the email address
- Check the product
- You should see "You have already subscribed to notifications on this item!" 

### 4. Please link to the relevant issues (if any).

### 5. Which documentation changes (if any) need to be made because of this PR?

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

2024-01-09 13:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware5/shopware?pullRequest=2627) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopware5/shopware?pullRequest=2627) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware5/shopware?pullRequest=2627) it.</sub>

2024-01-09 14:48 UTC, mitelg requested changes
thanks for your contribution @kayaArvatis :+1: 

your changes look good so far. Would you mind adding a test for this? 
there is already a test, setting up the plugin here: https://github.com/shopware5/shopware/blob/5.7/tests/Functional/Plugins/Frontend/NotificationTest.php

2024-01-09 14:48 UTC, mitelg commented on engine/Shopware/Plugins/Default/Frontend/Notification/Bootstrap.php
> +            $ordernumbers = $this->get(Connection::class)->fetchAllAssociative($sql, [$id]);
```suggestion
            $ordernumbers = $this->get(Connection::class)->fetchAssociative($sql, [$id]);
```

that should give you a list of order numbers directly. so you do not need to iterate again, for picking the order numbers

2024-01-09 14:48 UTC, mitelg commented on engine/Shopware/Plugins/Default/Frontend/Notification/Bootstrap.php
> +                        if ($ordernumber === $sArticle['ordernumber']) {
good catch :ok_hand:

2024-01-10 13:13 UTC, kayaArvatis commented on engine/Shopware/Plugins/Default/Frontend/Notification/Bootstrap.php
> +            $ordernumbers = $this->get(Connection::class)->fetchAllAssociative($sql, [$id]);
@mitelg `fetchAssociative` returns only one order number but `fetchAllAssociative` returns all order numbers for the product it contains all variant order numbers, not sure what exactly is expected here

2024-01-10 13:15 UTC, kayaArvatis commented
@mitelg Thanks for your feedback, i will take a look at the tests

2024-01-10 16:35 UTC, kayaArvatis commented
Hi @mitelg I have applied the changes and added an test

2024-01-11 13:57 UTC, merged

2024-01-11 13:57 UTC, mitelg commented
thanks for your contribution @kayaArvatis 👍🎉💙