fix: media name and description usage
shopware5/shopware pull request #2631
Opened 2024-02-19 10:35 UTC by lacknere

### 1. Why is this change necessary?
Media name and description are not correctly mapped.

### 2. What does this change do, exactly?
* Fix the hydration and conversion of media name and description.
* Add media name fallbacks if no description is available.

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).

### 5. Which documentation changes (if any) need to be made because of this PR?

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2024-02-19 13:44 UTC, mitelg requested changes
thanks for your contribution, nice fix! 
would you mind adding a few tests?

2024-02-19 13:44 UTC, mitelg commented on UPGRADE-5.7.md
> +* Added image name fallbacks if no image description is available to:
```suggestion
* Added fallback to image name for `alt` and `title` attributes if image description is not available in following templates:
```

and then please list the tpl files and then the block names

2024-02-19 13:44 UTC, mitelg commented on engine/Shopware/Bundle/StoreFrontBundle/Gateway/DBAL/Hydrator/MediaHydrator.php
> +        $media->setName($data['__image_img']);
would you mind extending the `\Shopware\Tests\Functional\Bundle\StoreFrontBundle\ProductMediaTest`? so we can ensure, this behaviour stays in the future

2024-02-19 13:44 UTC, mitelg commented on engine/Shopware/Components/Compatibility/LegacyStructConverter.php
> +            'name' => $media->getName(),
please also extend the `\Shopware\Tests\Unit\Components\Compatibility\LegacyStructConverterTest`

2024-02-19 13:44 UTC, mitelg commented on themes/Frontend/Bare/frontend/index/index.tpl
> +            {$lastSeenProductsConfig.currentArticle.imageTitle = $sArticle.image.name}
don't we need to escape here as well? :thinking:

2024-02-19 18:08 UTC, lacknere commented on themes/Frontend/Bare/frontend/index/index.tpl
> +            {$lastSeenProductsConfig.currentArticle.imageTitle = $sArticle.image.name}
`$lastSeenProductsConfig`  is json encoded [here](https://github.com/shopware5/shopware/blob/40b94b7027d717cc2b9c9f93a0e1d7a73928232f/themes/Frontend/Bare/frontend/index/index.tpl#L250) so it should be escaped anyways, I think 🤔

2024-02-20 06:48 UTC, ennasus4sun approved these changes

2024-02-21 09:15 UTC, mitelg requested changes

2024-02-21 09:15 UTC, mitelg commented on engine/Shopware/Bundle/StoreFrontBundle/Gateway/DBAL/Hydrator/MediaHydrator.php
> +        $media->setName($data['__image_img']);
hey @lacknere 

I had another though about that. This change is a break. People and code are assuming, that the "name" contains the image description, if this hydration method is used. If we now change this, their code will break. So unfortunately we cannot merge it like that

2024-02-21 11:38 UTC, lacknere commented on engine/Shopware/Bundle/StoreFrontBundle/Gateway/DBAL/Hydrator/MediaHydrator.php
> +        $media->setName($data['__image_img']);
What about using description primarily and name as a fallback there, if no description is available? Something like `$media->setName($data['__image_description'] ?: $data['__image_img']);`

2024-02-26 21:29 UTC, mitelg commented on engine/Shopware/Bundle/StoreFrontBundle/Gateway/DBAL/Hydrator/MediaHydrator.php
> +        $media->setName($data['__image_img']);
sorry for the late answer :see_no_evil: 

I am not sure, if this is also a desired state :thinking: could also lead to unexpected behaviour, where not values where before. 

what about deprecating the old behaviour and trigger the new one with a parameter? :thinking: where the default ensures the old behaviour. 

to not break the public method, we would need to add the parameter commented at first, and get the value with https://www.php.net/manual/en/function.func-get-args.php :thinking: 

maybe you can find a way to build it like that, that you have the possibility to get the hydrated media with "correct" values, but the default way stays at it is.

2024-03-23 16:54 UTC, mitelg commented
hey @lacknere 
are you still on this? what are your thoughts?

2024-04-05 12:48 UTC, mitelg commented
Hey @lacknere 

I will close this PR due to inactivity. Let me know, if you want to discuss this further :slightly_smiling_face:

2024-04-05 12:48 UTC, closed without merging