fix: backend statistics notification pagination
shopware5/shopware pull request #2649
Opened 2024-03-30 15:22 UTC by Dominikrt

### 1. Why is this change necessary?
The pagination of the notification module is broken. The first page has no limit and the second page shows wrong total results.

### 2. What does this change do, exactly?
The `start` property can now be 0.

The total results get now count from SQL Server and not in php code.

### 3. Describe each step to reproduce the issue or behaviour.
signup for over 21 article notification and the pagination will not work

### 4. Please link to the relevant issues (if any).

### 5. Which documentation changes (if any) need to be made because of this PR?

### 6. Checklist

- [X] I have written tests and verified that they fail without my change
- [X] I have squashed any insignificant commits
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

2024-04-02 09:31 UTC, mitelg commented
hey @Dominikrt 

thanks again for your contribution! :tada: :+1: 

unfortunately we did not manage to get the pipeline running again yet. but we are on it

2024-04-02 09:37 UTC, mitelg requested changes

2024-04-02 09:37 UTC, mitelg commented on engine/Shopware/Controllers/Backend/Notification.php
> +            $totalCount = $repository->getArticleWithNotificationCountQuery()->getOneOrNullResult(AbstractQuery::HYDRATE_SINGLE_SCALAR);
```suggestion
            $totalCount = (int) $repository->getArticleWithNotificationCountQuery()->getOneOrNullResult(AbstractQuery::HYDRATE_SINGLE_SCALAR);
```

do the cast here and not where the variable is assigned to another one

2024-04-02 09:37 UTC, mitelg commented on engine/Shopware/Controllers/Backend/Notification.php
> +            /** @var ArticleRepository $repository */
please do not add var annotations if not necessary

2024-04-02 09:37 UTC, mitelg commented on engine/Shopware/Controllers/Backend/Notification.php
> +            /** @var ArticleRepository $repository */
please do not add var annotations if not necessary

2024-04-02 09:37 UTC, mitelg commented on tests/Functional/Controllers/Backend/NotificationTest.php
> +        static::assertEquals(self::NOTIFICATION_LIST_TOTAL_RESULTS, $this->View()->totalCount);
```suggestion
        static::assertEquals(self::NOTIFICATION_LIST_TOTAL_RESULTS, $this->View()->getAssign('totalCount'));
```

do not use magic property access, but this should also be comment on by PHPStan if the pipeline would run :grimacing:

2024-04-02 09:37 UTC, mitelg commented on tests/Functional/Controllers/Backend/NotificationTest.php
> +    private const NOTIFICATION_LIST_PAGINATION_START_1 = 0;
you should name the constants after the usage in the respective test. and not just 1, 2 and so on.

2024-04-02 09:37 UTC, mitelg commented on tests/Functional/Controllers/Backend/NotificationTest.php
> +        static::assertEquals(self::NOTIFICATION_LIST_TOTAL_RESULTS, $this->View()->totalCount);
please use `assertSame` as this ensures that the type is also the same

2024-04-02 12:21 UTC, Dominikrt commented on engine/Shopware/Controllers/Backend/Notification.php
> +            /** @var ArticleRepository $repository */
Hi, thank you for the feedback. 

How to decide if a var annotations is necessary? autocomplete isn't working without the annotation 🤔

2024-04-02 13:26 UTC, mitelg commented on engine/Shopware/Controllers/Backend/Notification.php
> +            /** @var ArticleRepository $repository */
adding a var annotation should only be the last resort, if the variable type could not be determined by PHPStan. in this case, PHPStan knows the variable. you may want to install the PHPStorm Symfony extension, which has some support for services directly received from the DI container

2024-04-02 14:34 UTC, mitelg commented
after a rebase the CI should work again

2024-04-06 18:58 UTC, Dominikrt commented
Hi @mitelg,
thank you for you're recommendations

I have also add an additional test to check the second page with the customer list.

2024-04-08 08:34 UTC, mitelg requested changes
just a few more tiny things :blush: 

and a rebase of your branch would be nice

2024-04-08 08:34 UTC, mitelg commented on engine/Shopware/Controllers/Backend/Notification.php
> +    public function getArticleListAction(): void
please revert this, as this is considered as a breaking change.

to fix PHPStan you can add a return annotation to the PHPdoc

2024-04-08 08:34 UTC, mitelg commented on engine/Shopware/Controllers/Backend/Notification.php
> +    public function getCustomerListAction(): void
revert

2024-04-08 08:34 UTC, mitelg commented on engine/Shopware/Models/Article/Repository.php
> +    public function getArticleWithNotificationCountQuery(): Query
please do not use "article" if a product is meant. this is just a wrong translation and should be avoided. especially if new things are added

2024-04-08 08:34 UTC, mitelg commented on tests/Functional/Controllers/Backend/NotificationTest.php
> +    private const TEST_ARTICLE_LIST_LIMIT = 2;
sames as above, please exchange "article" with "product"

2024-04-08 08:34 UTC, mitelg commented on tests/Functional/Controllers/Backend/NotificationTest.php
> +    public function testGetArticleListFirstPage(): void
just FYI: no need to revert the void return type in the tests, as this is not part of the BC promise :wink:

2024-04-08 09:15 UTC, Dominikrt commented on engine/Shopware/Models/Article/Repository.php
> +    public function getArticleWithNotificationCountQuery(): Query
I think it makes things more confusing if everything is called `article` and I rename my new method to `product`.

But no problem I can rename it.

2024-04-08 11:34 UTC, mitelg commented on engine/Shopware/Models/Article/Repository.php
> +    public function getArticleWithNotificationCountQuery(): Query
the thing is "article" is already confusing everybody who is not coming from German or Netherlands language :wink: 

so naming it `getProductsWithNotifictionsCountQuery` is quite clear, imo

2024-04-09 18:53 UTC, Dominikrt commented
Hi @mitelg,
I commit the recommended changes, but it looks like we have pipeline problems again...

2024-04-09 20:02 UTC, mitelg approved these changes

2024-04-09 21:09 UTC, mitelg commented
after an update of a GitHub action, the e2e tests didn't work anymore. but they should run now again. please try to rebase :slightly_smiling_face: See https://github.com/shopware5/shopware/actions/runs/8611563619

Otherwise the changes look good :+1:

2024-05-16 11:02 UTC, merged

2024-05-16 11:03 UTC, mitelg commented
thanks for your contribution @Dominikrt 👍🎉💙