fix: backend voucher individual code search
shopware5/shopware pull request #2671
Opened 2024-04-24 17:50 UTC by Dominikrt

Hi,

### 1. Why is this change necessary?
the individual voucher code search is broken, after a reload the store lose its filter

### 2. What does this change do, exactly?
the last filter get cleared bevor and not after the search method.

### 3. Describe each step to reproduce the issue or behaviour.
open a individual voucher and search for a code, after a list reload the filter gets cleared.

### 4. Please link to the relevant issues (if any).

### 5. Which documentation changes (if any) need to be made because of this PR?

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [X] I have squashed any insignificant commits
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

2024-05-16 11:06 UTC, mitelg requested changes

2024-05-16 11:06 UTC, mitelg commented on themes/Backend/ExtJs/backend/voucher/controller/voucher.js
> +                codeStore.filters.clear();
I just merged https://github.com/shopware5/shopware/pull/2649

So I guess we need a rebase here

2024-05-16 11:06 UTC, mitelg commented on themes/Backend/ExtJs/backend/voucher/controller/code.js
> +            store.load();
why are you loading the store only, when the search string is not given? :thinking:

2024-05-16 11:08 UTC, mitelg commented on themes/Backend/ExtJs/backend/voucher/controller/voucher.js
> +                codeStore.filters.clear();
ah no, I mixed it up with https://github.com/shopware5/shopware/pull/2677 :see_no_evil:

2024-05-16 11:34 UTC, mitelg commented on themes/Backend/ExtJs/backend/voucher/controller/voucher.js
> +                codeStore.filters.clear();
but that will also be merged in a few minutes, so the rebase should really be necessary :grin:

2024-05-16 13:10 UTC, Dominikrt commented on themes/Backend/ExtJs/backend/voucher/controller/code.js
> +            store.load();
Hi, to load the entire list with no input (show all voucher codes). 
The filter functions do a store reload, its not needed to reload the store manually.

2024-05-21 08:51 UTC, mitelg approved these changes

2024-05-21 08:52 UTC, merged

2024-05-21 08:52 UTC, mitelg commented
thanks again for your contribution @Dominikrt 👍🎉💙