Fix/version compare deprecation
shopware5/shopware pull request #2688
Opened 2024-05-24 16:35 UTC by aragon999

### 1. Why is this change necessary?
This PR fixes two minor issues, on the one hand a typo in a command. On the other hand a PHP deprecation:
```
PHP Deprecated:  version_compare(): Passing null to parameter #2 ($version2) of type string is deprecated in .../engine/Shopware/Components/Plugin/Bootstrap.php on line 112
```
which occurs when a plugin from the legacy plugin structure is not present in the `s_core_plugins` table.

### 2. What does this change do, exactly?
Fix those issues.

### 3. Describe each step to reproduce the issue or behaviour.
\-

### 4. Please link to the relevant issues (if any).
\-

### 5. Which documentation changes (if any) need to be made because of this PR?
\-

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2024-05-27 07:29 UTC, mitelg requested changes

2024-05-27 07:29 UTC, mitelg commented on engine/Shopware/Components/Plugin/Bootstrap.php
> +            return true;
why don't you return false here? :thinking: 

and is there not a serious problem with the plugin, if the current version is not set? how could that happen?

2024-05-27 09:29 UTC, aragon999 commented on engine/Shopware/Components/Plugin/Bootstrap.php
> +            return true;
It only happens when a plugin is added, and has not yet been put into the `s_core_plugin` table, i.e. on the first plugin refresh, after the plugin has been added on the filesystem. Hence I thought, okay in that case always a new version is present. But maybe false is also more reasonable, and probably I should add a comment. 

What do you think?

2024-05-27 10:56 UTC, mitelg commented on engine/Shopware/Components/Plugin/Bootstrap.php
> +            return true;
I guess we should give the same value back, as the call of `version_compare` with `null` is giving back.

maybe you can add a small test case here https://github.com/shopware5/shopware/blob/5.7/tests/Functional/Components/Plugin/BootstrapTest.php so it is ensured, that the behaviour stays the same

2024-05-28 07:59 UTC, aragon999 commented on engine/Shopware/Components/Plugin/Bootstrap.php
> +            return true;
Yes the value is always true, if the second argument is `null`:
![image](https://github.com/shopware5/shopware/assets/6317761/55f72487-60fb-46f6-8a5a-67161a4236ae)

I will look into the tests though :-)

2024-05-28 08:08 UTC, mitelg commented on engine/Shopware/Components/Plugin/Bootstrap.php
> +            return true;
so returning true is okay? :grin:

2024-06-05 10:02 UTC, aragon999 commented on engine/Shopware/Components/Plugin/Bootstrap.php
> +            return true;
Yes, `true` is okay :-) I also added a test.

2024-06-05 11:46 UTC, mitelg requested changes

2024-06-05 11:46 UTC, mitelg commented on tests/Functional/Components/Plugin/BootstrapTest.php
> +        // current version, update version, expected
instead of writing a comment, you can also make the arrays associative with a speaking array key

```
        return [
            [
                'currentVersion' => '2.0.0',
                'updateVersion' => '2.0.0',
                'isNewer' => false
            ],
            [
                'currentVersion' => '1.0.0',
                'updateVersion' => '2.0.0',
                'isNewer' => true
            ],
            [
                'currentVersion' => null,
                'updateVersion' => '2.0.0',
                'isNewer' => true
            ],
            [
                'currentVersion' => '2.0.0',
                'updateVersion' => null,
                'isNewer' => false
            ],
            [
                'currentVersion' => '1',
                'updateVersion' => '1.0.0',
                'isNewer' => false
            ],
        ];
```

2024-06-05 11:46 UTC, mitelg commented on tests/Functional/Components/Plugin/BootstrapTest.php
> +    public function testHasNewerVersion(?string $currentVersion, ?string $updateVersion, bool $expected): void
```suggestion
    public function testHasNewerVersion(?string $currentVersion, ?string $updateVersion, bool $isNewer): void
```

2024-06-05 11:46 UTC, mitelg commented on engine/Shopware/Components/Plugin/Bootstrap.php
> +        if (empty($currentVersion)) {
as you are using `empty` here, we should also check how it behaves with empty string or `string(0)`

2024-06-05 11:46 UTC, mitelg commented
thanks for the update! just a few smaller improvement suggestions

2024-06-05 12:56 UTC, aragon999 commented on engine/Shopware/Components/Plugin/Bootstrap.php
> +        if (empty($currentVersion)) {
Ah yes, that would have been a "breaking" change :-) I adjusted the comparison to strictly compare against `null`. Furthermore I added two more test cases.

2024-06-05 15:21 UTC, mitelg approved these changes

2024-06-05 15:21 UTC, mitelg commented
thank you very much for your contribution @aragon999 👍🎉💙

2024-06-05 15:42 UTC, merged