Update phpstan to 1.11.11
shopware5/shopware pull request #2749
Opened 2024-08-19 15:07 UTC by aragon999

Supersedes https://github.com/shopware5/shopware/pull/2744

2024-08-20 06:59 UTC, mitelg requested changes

2024-08-20 06:59 UTC, mitelg commented on engine/Shopware/Controllers/Backend/Export.php
> +        if ($outputHandle === false) {
why did you change this? I like it more, if we explicitly check for what we need.

2024-08-26 12:38 UTC, aragon999 commented on engine/Shopware/Controllers/Backend/Export.php
> +        if ($outputHandle === false) {
So maybe this is a more philosophical question, but in this case the docs for [`fopen`](https://www.php.net/manual/en/function.fopen.php) state that
> Returns a file pointer resource on success, or [false](https://www.php.net/manual/en/reserved.constants.php#constant.false) on failure

So the return type is either a `resource` or `false`. As this `if` condition should only catch the error case, we should explicitly check for `false` as other cases (which currently do not exist) should be handled differently.

I can also revert the check in the `if` condition.

2024-08-26 21:15 UTC, mitelg commented on engine/Shopware/Controllers/Backend/Export.php
> +        if ($outputHandle === false) {
is fine for me, the check for is resource seems to be kind of tricky anyway. see https://github.com/phpstan/phpstan/issues/11498#issuecomment-2285536288

2024-08-26 21:16 UTC, mitelg approved these changes

2024-08-26 21:16 UTC, merged