chore(deps-dev): Bump phpstan/phpstan from 1.12.0 to 1.12.5
shopware5/shopware pull request #2766
Opened 2024-10-01 22:07 UTC by aragon999

and fix some phpstan errors

2024-10-02 06:46 UTC, mitelg requested changes
thank you very much again!

2024-10-02 06:46 UTC, mitelg commented on engine/Shopware/Commands/FirstRunWizardDisableCommand.php
> +        $elementId = is_numeric($elementId) ? (int) $elementId : 0;
wouldn't `false` be cast to `0` anyway?

2024-10-02 06:46 UTC, mitelg commented on engine/Shopware/Commands/FirstRunWizardDisableCommand.php
> +        $valueid = is_numeric($valueid) ? (int) $valueid : 0;
same as above

2024-10-02 06:46 UTC, mitelg commented on engine/Shopware/Commands/FirstRunWizardDisableCommand.php
> +    protected function configure(): void
I guess this would be a breaking change, strictly speaking :grimacing:

2024-10-02 06:46 UTC, mitelg commented on engine/Shopware/Commands/FirstRunWizardEnableCommand.php
> +    protected function configure(): void
same as above

2024-10-02 06:46 UTC, mitelg commented on engine/Shopware/Commands/FirstRunWizardEnableCommand.php
> +        $elementId = is_numeric($elementId) ? (int) $elementId : 0;
same as above

I see an abstraction potential here :grin:

2024-10-02 06:46 UTC, mitelg commented on engine/Shopware/Components/Plugin/CronjobSynchronizer.php
> +     * @param array<string> $cronjobActions
```suggestion
     * @param list<string> $cronjobActions
```

2024-10-02 06:46 UTC, mitelg commented on engine/Shopware/Components/Plugin/CronjobSynchronizer.php
> +     * @param array<array<string, mixed>> $cronjobs
really fancy would be an object shape annotation of the array :innocent:

2024-10-02 06:46 UTC, mitelg commented on tests/Functional/Bundle/StoreFrontBundle/ListProductTest.php
> -        foreach ($product->getPriceRules() as $price) {
can we check the rules in another way? that they are correctly present?

2024-10-02 07:56 UTC, aragon999 commented on engine/Shopware/Commands/FirstRunWizardDisableCommand.php
> +        $elementId = is_numeric($elementId) ? (int) $elementId : 0;
The problem is, that this version of doctrine returns `mixed|false`, therefore this check. But it probably should be replaced by `fetchOne` (which returns `mixed|false` as well).

2024-10-02 07:56 UTC, aragon999 commented on engine/Shopware/Commands/FirstRunWizardDisableCommand.php
> +    protected function configure(): void
Mh, does someone extend commands? But probably as they are not internal, it might be a BC.

2024-10-02 07:56 UTC, aragon999 commented on engine/Shopware/Commands/FirstRunWizardEnableCommand.php
> +        $elementId = is_numeric($elementId) ? (int) $elementId : 0;
Yes, I was thinking about this as well, but then we would have inherited commands and I was not sure where to place them, and then I thought, okay maybe for phpstan cleanup, it is enough to adjust it twice :D

2024-10-02 07:56 UTC, aragon999 commented on engine/Shopware/Components/Plugin/CronjobSynchronizer.php
> +     * @param array<array<string, mixed>> $cronjobs
Yeah, I will look into it, I still need to adjust the code, that the pipeline for php 7.4 still works :-)

2024-11-13 15:57 UTC, mitelg commented
superseded by https://github.com/shopware5/shopware/pull/2812

sorry @aragon999 :see_no_evil:

2024-11-13 15:57 UTC, closed without merging