Fixed output of '0' in xml convert
shopware5/shopware pull request #418
Opened 2016-01-25 12:31 UTC by shyim

I am currently building a export of orders, but all fields where the value is 0 will be droped. This Pull Request will solve the issue

2017-03-21 14:31 UTC, roman-1983 requested changes
use `isset()` instead

2017-03-21 14:31 UTC, roman-1983 commented on engine/Shopware/Components/Convert/Xml.php
> +            if (empty($item) && $item != 0) {
Why don't you use `isset()` instead?

2017-03-21 14:51 UTC, shyim commented on engine/Shopware/Components/Convert/Xml.php
> +            if (empty($item) && $item != 0) {
We have 2017 i can't say why.
I guess this pr will never be merged. This class is Deprecated in 5.3

2017-04-04 06:44 UTC, janbuecker commented
We decided to close this PR because of time constraints and limited overall benefit to the product.

2017-04-04 06:44 UTC, closed without merging