Remove customergroup blocked articles in basket
shopware5/shopware pull request #697
Opened 2016-09-01 11:59 UTC by shyim

| Questions        | Answers
| ---------------- | -------------------------------------------------------
| BC breaks?       | no
| Tests pass?      | yes
| Related tickets? | There was a issue. i cant find it lel
| How to test?     | Add article to cart which is blocked for merchants, login to a merchant account in checkout and the article should be removed

## Description
Please describe your pull request:

We had some troubles with customers, because some products are blocked for merchants and merchants has ordered the products with that bug :)

2016-09-30 11:43 UTC, janbuecker commented
We should prevent adding it too. So please consider this case in `sAddArticle()`.

2016-09-30 20:34 UTC, shyim commented
@janbuecker added

2016-10-08 10:19 UTC, dnoegel commented
This will currently iterate all items in the basket and perform those queries. This should be changed in a way, that only one query is needed to determine all items, which need to be removed. The deletion of items then could happen in a transaction, for example.

2016-10-20 18:28 UTC, shyim commented
@dnoegel updated :)

2016-10-21 06:28 UTC, mitelg requested changes

2016-10-21 06:28 UTC, mitelg commented on engine/Shopware/Core/sBasket.php
> +        return $this->db->fetchOne('SELECT 1 FROM s_articles_avoid_customergroups WHERE customergroupId = ? AND articleID = ?', [
I think it is more readable, if you use something like :customerGroupId instead of ?

2016-10-23 10:58 UTC, shyim commented on engine/Shopware/Core/sBasket.php
> +        return $this->db->fetchOne('SELECT 1 FROM s_articles_avoid_customergroups WHERE customergroupId = ? AND articleID = ?', [
Aye Aye, Captain!

2016-10-24 08:20 UTC, mitelg approved these changes

2017-05-15 09:53 UTC, janbuecker commented
We've changed the code entirely so that it resulted in a new commit 474703992c4e2b91e5a099798737b6b5a4804bb4.

2017-05-15 09:53 UTC, closed without merging