[Papercut][SW-15897]
shopware5/shopware pull request #712
Opened 2016-09-06 19:23 UTC by shyim

## Description
Please describe your pull request:
It makes possible to use html mails in status mails

| Questions        | Answers
| ---------------- | -------------------------------------------------------
| BC breaks?       | no
| Tests pass?      | yes
| Related tickets? | [SW-15897](https://issues.shopware.com/#/issues/SW-15897)
| How to test?     | Write to a status mail a html content and change a order to that status

2016-09-13 09:25 UTC, janbuecker commented on engine/Shopware/Controllers/Backend/Order.php
> +                    'isHtml' => (bool) Shopware()->Db()->fetchOne('SELECT `ishtml` FROM s_core_config_mails WHERE `name` = ?', [
I think you can replace the SQL statement with something like `!empty($mail->getBodyHtml())` since the `bodyHtml` property of the mail object only gets filled, if the template's `isHtml` is `true`.

2016-09-15 06:20 UTC, janbuecker commented on engine/Shopware/Controllers/Backend/Order.php
> +                    'isHtml' => !empty($mail->getPlainBody()),
Why do you use `getPlainBody()` instead of `getBodyHtml()` here? Don't you want to check against html mails? Have you tested your code afterwards?

2016-09-15 06:21 UTC, janbuecker requested changes

2016-09-18 09:21 UTC, shyim commented on engine/Shopware/Controllers/Backend/Order.php
> +                    'isHtml' => !empty($mail->getPlainBody()),
Done

2016-09-18 09:26 UTC, shyim commented on engine/Shopware/Controllers/Backend/Order.php
> +                    'isHtml' => !empty($mail->getPlainBody()),
getPlainBody returns the html as string, getBodyHtml returns a Zend_Mime_Part :) Yes i tested the code
setter: https://github.com/shopware/shopware/blob/5.2/engine/Library/Enlight/Components/Mail.php#L198
getter:
https://github.com/shopware/shopware/blob/5.2/engine/Library/Enlight/Components/Mail.php#L209

2016-09-20 11:20 UTC, janbuecker approved these changes

2016-09-20 11:21 UTC, merged