[Papercut][SW-10346] - Add cronjob configuration field to keep cronjobs enabled after errors during execution
shopware5/shopware pull request #737
Opened 2016-09-09 13:30 UTC by kleinmann

This adds a new configuration option for cronjobs to tell whether the job should be disabled if an error occurs during its execution. The option is enabled by default to keep backwards compatibility with the existing behaviour.

The motivation behind this is that cronjobs communicating with external services may crash due to intermittent connection issues or errors in the external service. These jobs should stay enabled so the next run is able to "fix" these issues.

I have also added a new event based on the cronjob name to allow shop owners to handle errors of default or third-party cronjobs within their own plugins.

| Questions        | Answers
| ---------------- | -------------------------------------------------------
| BC breaks?       | no
| Tests pass?      | yes
| Related tickets? | https://issues.shopware.com/#/issues/SW-10346
| How to test?     | Create a new cronjob that throws an exception during execution. Uncheck the new checkbox, execute the job. The job should be disabled. Re-enable the job, set the checkbox and re-run the job. The job should now stay enabled even after the error.

2016-09-09 14:04 UTC, shyim commented on engine/Shopware/Components/Plugin/Bootstrap.php
> +                'disable_on_error' => 1,
New function parameter were cool, to configure "disable_on_error" while creating new cronjob :)

2016-09-09 14:57 UTC, kleinmann commented on engine/Shopware/Components/Plugin/Bootstrap.php
> +                'disable_on_error' => 1,
Good catch! Updated the PR accordingly.

2016-09-15 09:26 UTC, janbuecker requested changes

2016-09-15 09:26 UTC, janbuecker commented on _sql/migrations/786-add-crontab-disableonerror.php
> +    INSERT IGNORE INTO `s_core_snippets` (`namespace`, `shopID`, `localeID`, `name`, `value`, `created`, `updated`)
please don't manage snippets yourself using migrations. you can use the snippet files in the `/snippets` folder.

2016-09-16 09:13 UTC, kleinmann commented on _sql/migrations/786-add-crontab-disableonerror.php
> +    INSERT IGNORE INTO `s_core_snippets` (`namespace`, `shopID`, `localeID`, `name`, `value`, `created`, `updated`)
Thanks for the feedback, must have overlooked that folder. Some differences between the Shopware distribution and the Shopware repository can be missed :-)
I added a new commit accordingly.

2016-09-19 05:53 UTC, merged

2016-09-19 05:53 UTC, janbuecker commented
Thanks for your work! 👍