Add phone to order shipping address model
shopware5/shopware pull request #891
Opened 2016-12-21 12:46 UTC by FiveDigital

You can enter a phone number for you shipping address but it won't be persisted since the column is missing in the model/database. 

| Questions        | Answers
| ---------------- | -------------------------------------------------------
| BC breaks?       | no
| Tests pass?      | yes
| Related tickets? | no
| How to test?     | Enter a phone number in your shipping address. After placing the order the phone number is saved in the `s_order_shippingaddress` table.

2016-12-21 13:02 UTC, mitelg commented
hey @FiveDigital 
thanks for your PR. please have a look at the tests. some of them are failing due to your changes

2016-12-21 13:04 UTC, FiveDigital commented
The CI says: 
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 's11_.phone' in 'field list'

I have added the column in my migration. Perhaps the migration is not applied? Do I have to do more than just add the migration file?

2016-12-21 13:08 UTC, mitelg commented
the latest migration number is 809. so you have to change it, to at least 810
otherwise the migration number is duplicated and will have no affect

2016-12-21 13:31 UTC, FiveDigital commented
Okay that fixed the problem :) I don't know why I chose the wrong migration number.

2016-12-21 14:18 UTC, FiveDigital commented
@mitelg All green now 👍

2016-12-22 12:50 UTC, mitelg commented
hey @FiveDigital 
after talking with my colleagues, we think there are still missing some things. a new field must be nullable and the new field will not show up in the backend. after you have changed your PR we could schedule it.

2016-12-22 13:09 UTC, FiveDigital commented
Done 👍

2016-12-22 13:14 UTC, mitelg requested changes

2016-12-22 13:14 UTC, mitelg commented on engine/Shopware/Models/Order/Shipping.php
> +     * @ORM\Column(name="phone", type="string", length=40, nullable=false)
remove the nullable parameter

2016-12-22 13:27 UTC, FiveDigital commented
Done 👍

2016-12-22 13:30 UTC, mitelg approved these changes

2016-12-22 13:33 UTC, mitelg commented
oh, the tests are failing :see_no_evil:

2016-12-22 13:56 UTC, FiveDigital commented
Ah new migration was added in the meantime so I have renamed my new one and rebased the PR.

2017-06-26 08:11 UTC, FiveDigital commented
@mitelg Will this be merged in 5.2 or should I rebase/recreate this PR for 5.3?

2017-06-26 08:19 UTC, mitelg commented
@FiveDigital I don't think we are going to merge this in 5.2. 
If you like, you can do a rebase. otherwise we will cherry pick your commit :wink:

2017-06-26 08:25 UTC, FiveDigital commented
I have created a new PR for 5.3 https://github.com/shopware/shopware/pull/1172

2017-06-26 08:25 UTC, closed without merging