Added payment attributes
shopware5/shopware pull request #929
Opened 2017-01-25 21:18 UTC by shyim

## Description
Please describe your pull request:
* Why is it necessary?
Work with attributes in frontend
* What does it improve?
Adds attribute
* Does it have side effects?
Nope

| Questions        | Answers
| ---------------- | -------------------------------------------------------
| BC breaks?       | no
| Tests pass?      | yes
| Related tickets? | 
| How to test?     | debug vars

2017-01-25 22:05 UTC, shyim commented
@janbuecker again restart :o

2017-01-27 07:58 UTC, OliverSkroblin commented on engine/Shopware/Core/sAdmin.php
> +        foreach ($getPaymentMeans as &$getPaymentMean) {
Hi @shyim,
store front attributes are a little bit tricky ;).
To implement store front attributes you have to consider the following things:
- Added leftJoin query to initial data query (in this case: https://github.com/shopware/shopware/pull/929/files#diff-0a0564f026f3b27a8946fc6e96862a4bR208)
- Consider translations for all attributes which are stored differently. As own s_core_translation entry with table name as object key or inside the main entity translation like `article` or `variant`.
- Don't execute sql queries in loops to prevent unnecessary server load

My solution here would be to implement a new service and gateway for payments inside the store front bundle and load data there. The FieldHelper and attribute hydrator has different helper function to simplify attribute loading.

If you have fun and time you can implement this to ;)

Service and gateway should only have a "getList" function with $ids and ShopContextInerface parameter, like the other gateways =)

2017-01-28 22:58 UTC, shyim commented
@OliverSkroblin I have built now a PaymentStruct, Hydrator and Interface like the other in StoreFront :). I moved also the logic from sAdmin to the Service.

Have you a idea why the last test fails?

2017-01-31 06:46 UTC, janbuecker requested changes

2017-01-31 06:46 UTC, janbuecker commented on engine/Shopware/Bundle/StoreFrontBundle/Gateway/DBAL/Hydrator/PaymentHydrator.php
> +        $translation = $this->getTranslation($data, '__payment');
The translations are merged. You can get rid of the next few lines by adding additional parameters.

```php
$translation = $this->getTranslation($data, '__payment', [], $data['__payment_id']);
```

2017-01-31 06:46 UTC, janbuecker commented on engine/Shopware/Bundle/StoreFrontBundle/Gateway/DBAL/PaymentGateway.php
> +        $sEsd = Shopware()->Modules()->Basket()->sCheckForESD();
You don't want the dependency of the sBasket or Front controller here. Please move the whole logic back into the core classes and simply select the data needed for the payment you provide via PaymentService which you need to implement.

2017-01-31 06:46 UTC, janbuecker commented on engine/Shopware/Bundle/StoreFrontBundle/Gateway/PaymentGatewayInterface.php
> +    public function get($paymentId, Struct\ShopContextInterface $context, $fallback = false, $user = null);
Please do not implement a `get()` method. Only batch, only getList.

2017-01-31 06:46 UTC, janbuecker commented on engine/Shopware/Core/sAdmin.php
> +    private function convertToLegacyPaymentArray(Payment $payment)
Please move this method into the `LegacyStructConverter`

2017-01-31 19:23 UTC, shyim commented
@janbuecker changes are done. Travis is also green ❤️

2018-12-10 08:32 UTC, closed without merging