remove baseprice column
shopware5/shopware pull request #934
Opened 2017-01-30 09:22 UTC by jochenmanz

## Description
Please describe your pull request:
* Why is it necessary?
The baseprice column was removed from the price model in 5.2. This is only a small cleanup PR.
* What does it improve?
Database size
* Does it have side effects?
none

| Questions        | Answers
| ---------------- | -------------------------------------------------------
| BC breaks?       | no
| Tests pass?      | yes
| Related tickets? | none
| How to test?     | reinstall shopware from scratch or update an existing 5.2 installation. No baseprice column should be present in s_articles_prices

2017-01-30 10:13 UTC, mitelg requested changes

2017-01-30 10:13 UTC, mitelg commented on _sql/install/latest.sql
> -  `baseprice` double DEFAULT NULL,
don't change the install/latest.sql

2017-01-30 10:13 UTC, mitelg commented
the builds are failing, because you changed the latest.sql :wink:

2017-01-30 10:19 UTC, mitelg approved these changes

2017-01-30 10:29 UTC, shyim requested changes

2017-01-30 10:29 UTC, shyim commented on _sql/migrations/815-remove-base-price-column.php
> +        $statement = $this->connection->query('SELECT * FROM s_articles_prices');
SHOW COUMNS FROM s_articles_prices would be better here :)

2017-01-30 18:06 UTC, dnoegel commented
If we merge this, I'd suggest 5.3 due to the schema change.

2017-01-30 21:56 UTC, samuelvogel commented
Just for reference, why the field is currently still there: https://github.com/shopware/shopware/pull/527#issuecomment-218442872

2017-01-31 07:59 UTC, mitelg commented
@dnoegel yeah, we already discussed that. and we will do it on 5.3. IF we do it :wink: :smile:

2017-04-25 07:01 UTC, closed without merging