Fixed opcache check when opcache is disabled with php.ini
shopware5/shopware pull request #986
Opened 2017-02-18 11:57 UTC by shyim

## Description
Please describe your pull request:
* Why is it necessary?
Backend Module shows opcache is everything ok, but it is not enabled..
* What does it improve?
Checks opcache is also enabled in php.ini
* Does it have side effects?
Nope

PS: I have done also cosmetic changes

| Questions        | Answers
| ---------------- | -------------------------------------------------------
| BC breaks?       | no
| Tests pass?      | yes
| Related tickets? | [SW-17721](https://issues.shopware.com/issues/SW-17721)
| How to test?     |

2017-02-18 16:45 UTC, nlubisch requested changes

2017-02-18 16:45 UTC, nlubisch commented on engine/Shopware/Controllers/Backend/Performance.php
> +                'valid' => extension_loaded('Zend OPcache') === true && ini_get('opcache.enable') == 1 ? self::PERFORMANCE_VALID : self::PERFORMANCE_INVALID
you can better check the type with "===" too.
ini_get returns always a string if the key is there - only when its not there it returns false

2017-02-18 18:57 UTC, samuelvogel commented on engine/Shopware/Controllers/Backend/Performance.php
> +    protected $configData = [];
This PR is really hard to digest as it also contains a lot of (probably unwanted) PHP syntax / code style changes.

2017-02-19 12:13 UTC, nlubisch approved these changes

2017-03-01 13:40 UTC, soebbing commented
PR was merged with https://github.com/shopware/shopware/commit/9a2f16b12c828a477cd208a6f3dc453872c67e93

Thanks again for your help! @shyim 👍

2017-03-01 13:40 UTC, closed without merging